## 1. Create an sqlalchemy engine using a sample from the data set

In [8]:
import pandas as pd
from sqlalchemy import create_engine

In [9]:
a_data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",header=None)
a_data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [10]:
rename_col = ['age','workclass','fnlwgt','education','education_num','marital_status',
           'occupation','relationship','race','sex','capital_gain','capital_loss',
           'hours_per_week','native_country', 'income']

In [11]:
a_data.columns = rename_col
a_data.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [12]:
engine = create_engine('sqlite://', echo=False)

In [13]:
a_data.to_sql("adult",  con=engine, if_exists="replace",index=False)

## 2. Write two basic update queries

In [14]:
engine.execute('''update adult set "education" ="Bachelors" where "education"=" Undergraduate" ''')

In [15]:
engine.execute('''update adult set "marital_status" ="Single" where "marital_status"=" Never-married" ''')

## 3. Write two delete queries

In [16]:
engine.execute('''delete from adult where education_num=7 ''')

In [18]:
engine.execute('''delete from adult where education_num<5 ''')

## 4. Write two filter queries

In [59]:
filter1 = engine.execute('''select * from adult where age<20''')

for row in filter1:
    print (row)

(19, ' Private', 168294, ' HS-grad', 9, 'Single', ' Craft-repair', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 544091, ' HS-grad', 9, ' Married-AF-spouse', ' Adm-clerical', ' Wife', ' White', ' Female', 0, 0, 25, ' United-States', ' <=50K')
(18, ' Private', 226956, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 30, ' ?', ' <=50K')
(19, ' Private', 101509, ' Some-college', 10, 'Single', ' Prof-specialty', ' Own-child', ' White', ' Male', 0, 0, 32, ' United-States', ' <=50K')
(18, ' Private', 446839, ' HS-grad', 9, 'Single', ' Sales', ' Not-in-family', ' White', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(17, ' ?', 304873, ' 10th', 6, 'Single', ' ?', ' Own-child', ' White', ' Female', 34095, 0, 32, ' United-States', ' <=50K')
(19, ' Private', 301606, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' Black', ' Male', 0, 0, 35, ' United-States', ' <=50K')
(19, ' Private', 316868, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 30, ' Mexico', ' <=50K')
(18, ' Private', 183930, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 12, ' United-States', ' <=50K')
(19, ' ?', 170653, ' HS-grad', 9, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, ' Italy', ' <=50K')
(18, ' Private', 243313, ' HS-grad', 9, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Local-gov', 27382, ' Some-college', 10, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' ?', 218956, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 24, ' Canada', ' <=50K')
(17, ' Private', 191260, ' 9th', 5, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 1055, 0, 24, ' United-States', ' <=50K')
(19, ' ?', 860348, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' Black', ' Female', 0, 0, 25, ' United-States', ' <=50K')
(19, ' Private', 104112, ' HS-grad', 9, 'Single', ' Sales', ' Unmarried', ' Black', ' Male', 0, 0, 30, ' Haiti', ' <=50K')
(19, ' Private', 25429, ' Some-college', 10, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 16, ' United-States', ' <=50K')
(19, ' Private', 232392, ' HS-grad', 9, 'Single', ' Other-service', ' Other-relative', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 206399, ' HS-grad', 9, 'Single', ' Machine-op-inspct', ' Own-child', ' Black', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(17, ' Private', 211870, ' 9th', 5, 'Single', ' Other-service', ' Not-in-family', ' White', ' Male', 0, 0, 6, ' United-States', ' <=50K')
(19, ' Private', 249609, ' Some-college', 10, 'Single', ' Protective-serv', ' Own-child', ' White', ' Male', 0, 0, 8, ' United-States', ' <=50K')
(18, ' ?', 165532, ' 12th', 8, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 25, ' United-States', ' <=50K')
(19, ' Private', 217039, ' Some-college', 10, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Male', 0, 0, 28, ' United-States', ' <=50K')
(17, ' Private', 169658, ' 10th', 6, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 21, ' United-States', ' <=50K')
(19, ' Private', 262601, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 14, ' United-States', ' <=50K')
(17, ' Private', 102726, ' 12th', 8, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 16, ' United-States', ' <=50K')
(19, ' Private', 475028, ' HS-grad', 9, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' State-gov', 378418, ' HS-grad', 9, 'Single', ' Tech-support', ' Own-child', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 192453, ' Some-college', 10, 'Single', ' Other-service', ' Other-relative', ' White', ' Female', 0, 0, 25, ' United-States', ' <=50K')
(17, ' Private', 316929, ' 12th', 8, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(18, ' Private', 231193, ' 12th', 8, 'Single', ' Machine-op-inspct', ' Own-child', ' White', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(18, ' ?', 196061, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 33, ' United-States', ' <=50K')
(17, ' Private', 32607, ' 10th', 6, 'Single', ' Farming-fishing', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 376540, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Not-in-family', ' White', ' Female', 0, 0, 30, ' United-States', ' <=50K')
(19, ' ?', 52114, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Female', 0, 0, 10, ' United-States', ' <=50K')
(18, ' Private', 293227, ' HS-grad', 9, 'Single', ' Other-service', ' Not-in-family', ' White', ' Female', 0, 0, 45, ' United-States', ' <=50K')
(18, ' Private', 177722, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' ?', 117201, ' HS-grad', 9, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(19, ' ?', 241616, ' HS-grad', 9, 'Single', ' ?', ' Unmarried', ' White', ' Male', 0, 2001, 40, ' United-States', ' <=50K')
(19, ' Self-emp-not-inc', 36012, ' Some-college', 10, 'Single', ' Craft-repair', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Local-gov', 167816, ' HS-grad', 9, ' Divorced', ' Exec-managerial', ' Not-in-family', ' White', ' Female', 0, 0, 35, ' United-States', ' <=50K')
(19, ' ?', 80710, ' HS-grad', 9, 'Single', ' ?', ' Own-child', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 194608, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 187161, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 25, ' United-States', ' <=50K')
(18, ' Private', 240747, ' HS-grad', 9, 'Single', ' Machine-op-inspct', ' Own-child', ' White', ' Female', 0, 0, 40, ' Dominican-Republic', ' <=50K')
(17, ' ?', 138507, ' 10th', 6, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 119075, ' Some-college', 10, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 50, ' United-States', ' <=50K')
(19, ' ?', 194095, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Federal-gov', 234151, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Unmarried', ' Black', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(19, ' ?', 172582, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 50, ' United-States', ' <=50K')
(19, ' Private', 213644, ' HS-grad', 9, 'Single', ' Machine-op-inspct', ' Not-in-family', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(18, ' ?', 169882, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Female', 594, 0, 15, ' United-States', ' <=50K')
(17, ' ?', 333100, ' 10th', 6, 'Single', ' ?', ' Own-child', ' White', ' Male', 1055, 0, 30, ' United-States', ' <=50K')
(19, ' Private', 225775, ' Some-college', 10, 'Single', ' Adm-clerical', ' Not-in-family', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(17, ' Local-gov', 32124, ' 9th', 5, 'Single', ' Other-service', ' Own-child', ' Black', ' Male', 0, 0, 9, ' United-States', ' <=50K')
(17, ' Private', 163494, ' 10th', 6, 'Single', ' Sales', ' Own-child', ' White', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(17, ' Private', 130806, ' 10th', 6, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 24, ' United-States', ' <=50K')
(18, ' Private', 208447, ' 12th', 8, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 6, ' United-States', ' <=50K')
(19, ' ?', 62534, ' Bachelors', 13, 'Single', ' ?', ' Own-child', ' Black', ' Female', 0, 0, 40, ' Jamaica', ' <=50K')
(19, ' Private', 124265, ' Some-college', 10, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 323421, ' Some-college', 10, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(18, ' Private', 214617, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Male', 0, 0, 16, ' United-States', ' <=50K')
(19, ' Private', 375077, ' HS-grad', 9, 'Single', ' Sales', ' Own-child', ' White', ' Male', 0, 0, 50, ' United-States', ' <=50K')
(18, ' Private', 46247, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 15, ' United-States', ' <=50K')
(19, ' Private', 197384, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 10, ' United-States', ' <=50K')
(17, ' ?', 158762, ' 10th', 6, 'Single', ' ?', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(17, ' ?', 228373, ' 10th', 6, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(19, ' Private', 418324, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Male', 0, 0, 36, ' United-States', ' <=50K')
(19, ' ?', 263338, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 45, ' United-States', ' <=50K')
(19, ' Private', 286469, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 30, ' United-States', ' <=50K')
(18, ' Private', 152545, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 8, ' United-States', ' <=50K')
(19, ' Private', 365640, ' HS-grad', 9, 'Single', ' Priv-house-serv', ' Not-in-family', ' White', ' Female', 0, 0, 45, ' ?', ' <=50K')
(19, ' ?', 33487, ' Some-college', 10, 'Single', ' ?', ' Other-relative', ' Amer-Indian-Eskimo', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(17, ' Self-emp-not-inc', 60116, ' 10th', 6, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Male', 0, 0, 10, ' United-States', ' <=50K')
(19, ' Private', 354104, ' HS-grad', 9, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(19, ' Private', 125010, ' HS-grad', 9, 'Single', ' Farming-fishing', ' Own-child', ' White', ' Male', 0, 0, 45, ' United-States', ' <=50K')
(17, ' ?', 103810, ' 12th', 8, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 242941, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 1602, 10, ' United-States', ' <=50K')
(17, ' Private', 329783, ' 10th', 6, 'Single', ' Sales', ' Other-relative', ' White', ' Female', 0, 0, 10, ' United-States', ' <=50K')
(18, ' Private', 201901, ' HS-grad', 9, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Female', 0, 1719, 15, ' United-States', ' <=50K')
(19, ' Private', 43285, ' Some-college', 10, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(18, ' Private', 675421, ' 9th', 5, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 594, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 172893, ' Some-college', 10, 'Single', ' Exec-managerial', ' Own-child', ' White', ' Female', 0, 0, 30, ' United-States', ' <=50K')
(18, ' Private', 343059, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 55284, ' HS-grad', 9, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 35, ' United-States', ' <=50K')
(19, ' Private', 171306, ' HS-grad', 9, 'Single', ' Sales', ' Own-child', ' White', ' Male', 0, 0, 3, ' United-States', ' <=50K')
(19, ' ?', 356717, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Female', 0, 0, 25, ' United-States', ' <=50K')
(19, ' ?', 143867, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(18, ' Local-gov', 134935, ' 12th', 8, 'Single', ' Protective-serv', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' ?', 192773, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Female', 0, 0, 35, ' United-States', ' <=50K')
(19, ' Private', 129059, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' Black', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(19, ' Private', 446219, ' 10th', 6, 'Single', ' Sales', ' Unmarried', ' Black', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(18, ' Private', 80616, ' 10th', 6, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 27, ' United-States', ' <=50K')
(19, ' Private', 57067, ' HS-grad', 9, 'Single', ' Machine-op-inspct', ' Other-relative', ' White', ' Male', 0, 0, 45, ' United-States', ' <=50K')
(19, ' Private', 196857, ' HS-grad', 9, 'Single', ' Other-service', ' Not-in-family', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 115248, ' Some-college', 10, 'Single', ' Adm-clerical', ' Not-in-family', ' Asian-Pac-Islander', ' Male', 0, 0, 40, ' Vietnam', ' <=50K')
(18, ' Private', 280298, ' HS-grad', 9, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 24, ' United-States', ' <=50K')
(18, ' Private', 57413, ' Some-college', 10, ' Divorced', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 15, ' United-States', ' <=50K')
(19, ' Private', 280071, ' Some-college', 10, 'Single', ' Machine-op-inspct', ' Other-relative', ' White', ' Male', 0, 0, 50, ' United-States', ' <=50K')
(19, ' Private', 87653, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 25, ' United-States', ' <=50K')
(19, ' Private', 116562, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(18, ' Private', 387568, ' 10th', 6, 'Single', ' Sales', ' Own-child', ' White', ' Male', 0, 0, 10, ' United-States', ' <=50K')
(18, ' Local-gov', 36411, ' 12th', 8, 'Single', ' Prof-specialty', ' Own-child', ' White', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(17, ' ?', 179715, ' 10th', 6, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Federal-gov', 30559, ' HS-grad', 9, ' Married-AF-spouse', ' Sales', ' Wife', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(17, ' Private', 206010, ' 12th', 8, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 8, ' United-States', ' <=50K')
(19, ' Private', 89397, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(18, ' ?', 297396, ' HS-grad', 9, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 10, ' United-States', ' <=50K')
(19, ' ?', 145234, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(18, ' Private', 130849, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 15, ' United-States', ' <=50K')
(18, ' Private', 266287, ' 12th', 8, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 35, ' United-States', ' <=50K')
(18, ' Private', 179203, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 181546, ' Some-college', 10, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(17, ' ?', 110998, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' Asian-Pac-Islander', ' Female', 0, 0, 40, ' Philippines', ' <=50K')
(19, ' Private', 417657, ' HS-grad', 9, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 50, ' United-States', ' <=50K')
(19, ' Private', 383637, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 40425, ' Some-college', 10, 'Single', ' Sales', ' Not-in-family', ' White', ' Female', 0, 0, 28, ' United-States', ' <=50K')
(18, ' Private', 97963, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 30, ' United-States', ' <=50K')
(19, ' Private', 25429, ' Some-college', 10, 'Single', ' Sales', ' Not-in-family', ' White', ' Female', 0, 0, 25, ' United-States', ' <=50K')
(17, ' Private', 139183, ' 10th', 6, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 15, ' United-States', ' <=50K')
(18, ' ?', 139003, ' HS-grad', 9, 'Single', ' ?', ' Other-relative', ' Other', ' Female', 0, 0, 12, ' United-States', ' <=50K')
(18, ' Private', 43272, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(18, ' Private', 89478, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' ?', 188618, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Female', 0, 0, 25, ' United-States', ' <=50K')
(17, ' Private', 263746, ' 10th', 6, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 24, ' United-States', ' <=50K')
(18, ' Private', 174732, ' HS-grad', 9, 'Single', ' Other-service', ' Other-relative', ' Black', ' Male', 0, 0, 36, ' United-States', ' <=50K')
(19, ' ?', 37332, ' HS-grad', 9, 'Single', ' ?', ' Own-child', ' White', ' Female', 1055, 0, 12, ' United-States', ' <=50K')
(19, ' Private', 100999, ' Bachelors', 13, 'Single', ' Prof-specialty', ' Own-child', ' White', ' Female', 0, 0, 30, ' United-States', ' <=50K')
(19, ' Private', 182355, ' Some-college', 10, 'Single', ' Adm-clerical', ' Own-child', ' Black', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(17, ' Private', 130125, ' 10th', 6, 'Single', ' Other-service', ' Own-child', ' Amer-Indian-Eskimo', ' Female', 1055, 0, 20, ' United-States', ' <=50K')
(17, ' Private', 354201, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(18, ' Private', 104704, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Own-child', ' Black', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Self-emp-not-inc', 206599, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 22, ' United-States', ' <=50K')
(18, ' ?', 298133, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(18, ' Private', 148644, ' HS-grad', 9, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 28, ' United-States', ' <=50K')
(19, ' Private', 202673, ' Some-college', 10, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 50, ' United-States', ' <=50K')
(19, ' Private', 52372, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(19, ' ?', 423863, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Female', 0, 0, 35, ' United-States', ' <=50K')
(19, ' Private', 38619, ' Some-college', 10, 'Single', ' Farming-fishing', ' Own-child', ' White', ' Male', 0, 0, 66, ' United-States', ' <=50K')
(19, ' Private', 306467, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' ?', 174233, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' Black', ' Male', 0, 0, 24, ' United-States', ' <=50K')
(18, ' ?', 437851, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 251579, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 14, ' United-States', ' <=50K')
(19, ' State-gov', 73009, ' Some-college', 10, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Male', 0, 0, 15, ' United-States', ' <=50K')
(19, ' Private', 376240, ' HS-grad', 9, 'Single', ' Machine-op-inspct', ' Own-child', ' White', ' Male', 0, 0, 42, ' United-States', ' <=50K')

(17, ' Private', 232713, ' 10th', 6, 'Single', ' Craft-repair', ' Not-in-family', ' White', ' Male', 594, 0, 30, ' United-States', ' <=50K')
(19, ' Private', 140985, ' Some-college', 10, 'Single', ' Adm-clerical', ' Other-relative', ' White', ' Male', 0, 0, 25, ' United-States', ' <=50K')
(19, ' Private', 268392, ' HS-grad', 9, 'Single', ' Sales', ' Unmarried', ' Black', ' Female', 0, 0, 30, ' United-States', ' <=50K')
(19, ' State-gov', 37332, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Not-in-family', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 35865, ' Some-college', 10, 'Single', ' Other-service', ' Not-in-family', ' White', ' Female', 0, 0, 30, ' United-States', ' <=50K')
(18, ' Private', 126125, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 376683, ' Some-college', 10, 'Single', ' Other-service', ' Unmarried', ' Black', ' Female', 2036, 0, 30, ' United-States', ' <=50K')
(18, ' Private', 166889, ' Some-college', 10, 'Single', ' Handlers-cleaners', ' Own-child', ' Black', ' Female', 0, 1602, 35, ' United-States', ' <=50K')
(19, ' Local-gov', 176831, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' Black', ' Female', 0, 0, 35, ' United-States', ' <=50K')
(17, ' Private', 178953, ' 12th', 8, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(18, ' Private', 31983, ' 12th', 8, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' ?', 217194, ' 10th', 6, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(19, ' Private', 150553, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' Asian-Pac-Islander', ' Female', 0, 0, 18, ' Philippines', ' <=50K')
(19, ' Private', 235909, ' Some-college', 10, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 286435, ' Some-college', 10, 'Single', ' Craft-repair', ' Own-child', ' White', ' Male', 594, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 574271, ' HS-grad', 9, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 28, ' United-States', ' <=50K')
(17, ' Private', 394176, ' 10th', 6, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(18, ' Private', 74539, ' 10th', 6, 'Single', ' Sales', ' Not-in-family', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 84610, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 30, ' United-States', ' <=50K')
(19, ' Private', 389942, ' HS-grad', 9, 'Single', ' Sales', ' Not-in-family', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 170720, ' HS-grad', 9, 'Single', ' Sales', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 205830, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 40, ' El-Salvador', ' <=50K')
(19, ' Private', 194905, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 30, ' United-States', ' <=50K')
(19, ' Private', 102723, ' Some-college', 10, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 106306, ' Some-college', 10, ' Divorced', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 198459, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Male', 0, 2001, 40, ' United-States', ' <=50K')
(18, ' Private', 184693, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 20, ' Mexico', ' <=50K')
(17, ' Private', 32763, ' 10th', 6, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 15, ' United-States', ' <=50K')
(18, ' Private', 165316, ' HS-grad', 9, 'Single', ' Transport-moving', ' Own-child', ' White', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(17, ' Private', 41865, ' 10th', 6, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 25, ' United-States', ' <=50K')
(17, ' Private', 25690, ' 10th', 6, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 10, ' United-States', ' <=50K')
(19, ' State-gov', 194260, ' Some-college', 10, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 15, ' United-States', ' <=50K')
(18, ' Private', 396270, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Male', 0, 0, 25, ' United-States', ' <=50K')
(18, ' Private', 120029, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(18, ' Private', 83451, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 30, ' United-States', ' <=50K')
(17, ' Private', 321880, ' 10th', 6, 'Single', ' Other-service', ' Own-child', ' Black', ' Male', 0, 0, 15, ' United-States', ' <=50K')
(19, ' Private', 118306, ' HS-grad', 9, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 16, ' United-States', ' <=50K')
(17, ' Private', 202521, ' 10th', 6, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 15, ' United-States', ' <=50K')
(18, ' Private', 25837, ' HS-grad', 9, 'Single', ' Other-service', ' Not-in-family', ' White', ' Male', 0, 0, 25, ' United-States', ' <=50K')
(19, ' Private', 181572, ' Some-college', 10, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 269991, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 40, ' Puerto-Rico', ' <=50K')
(19, ' Private', 351802, ' HS-grad', 9, 'Single', ' Machine-op-inspct', ' Own-child', ' White', ' Male', 0, 0, 35, ' United-States', ' <=50K')
(17, ' Private', 153021, ' 12th', 8, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 410543, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Not-in-family', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(17, ' ?', 212125, ' 10th', 6, 'Single', ' ?', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 196857, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(18, ' ?', 172214, ' HS-grad', 9, 'Single', ' ?', ' Own-child', ' Black', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 63434, ' 12th', 8, 'Single', ' Farming-fishing', ' Own-child', ' White', ' Female', 0, 0, 30, ' United-States', ' <=50K')
(19, ' Private', 183589, ' Some-college', 10, 'Single', ' Transport-moving', ' Own-child', ' White', ' Male', 0, 0, 25, ' United-States', ' <=50K')
(17, ' Private', 276718, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(18, ' Private', 89419, ' HS-grad', 9, 'Single', ' Tech-support', ' Own-child', ' White', ' Female', 0, 0, 10, ' United-States', ' <=50K')
(19, ' Private', 175507, ' HS-grad', 9, 'Single', ' Other-service', ' Not-in-family', ' White', ' Female', 0, 0, 30, ' United-States', ' <=50K')
(19, ' Private', 128346, ' HS-grad', 9, 'Single', ' Machine-op-inspct', ' Own-child', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(17, ' Private', 63734, ' 10th', 6, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(18, ' Private', 111256, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 229756, ' HS-grad', 9, 'Single', ' Sales', ' Own-child', ' White', ' Male', 0, 0, 50, ' United-States', ' <=50K')
(17, ' Private', 239346, ' 10th', 6, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 18, ' United-States', ' <=50K')
(19, ' Private', 238969, ' HS-grad', 9, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 10, ' United-States', ' <=50K')
(19, ' Private', 124486, ' 12th', 8, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 1602, 20, ' United-States', ' <=50K')
(19, ' ?', 199495, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 60, ' United-States', ' <=50K')
(19, ' Private', 118535, ' 12th', 8, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 18, ' United-States', ' <=50K')
(18, ' Private', 189487, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 35, ' United-States', ' <=50K')
(19, ' Private', 277695, ' 9th', 5, 'Single', ' Farming-fishing', ' Other-relative', ' White', ' Male', 0, 0, 16, ' Mexico', ' <=50K')
(19, ' Private', 236940, ' HS-grad', 9, 'Single', ' Farming-fishing', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 228939, ' HS-grad', 9, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 35, ' United-States', ' <=50K')
(18, ' Private', 162840, ' 12th', 8, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(18, ' ?', 126154, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(18, ' ?', 67793, ' HS-grad', 9, 'Single', ' ?', ' Own-child', ' White', ' Female', 0, 0, 60, ' United-States', ' <=50K')
(18, ' ?', 71076, ' HS-grad', 9, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' ?', 257343, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 361341, ' 12th', 8, 'Single', ' Prof-specialty', ' Not-in-family', ' Asian-Pac-Islander', ' Female', 0, 0, 25, ' Thailand', ' <=50K')
(19, ' Private', 163015, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 43003, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(17, ' Private', 167658, ' 12th', 8, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 6, ' United-States', ' <=50K')
(18, ' Private', 164441, ' Some-college', 10, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 38, ' United-States', ' <=50K')
(19, ' Self-emp-inc', 148955, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' Asian-Pac-Islander', ' Female', 0, 0, 35, ' South', ' <=50K')
(17, ' Private', 241185, ' 12th', 8, 'Single', ' Prof-specialty', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(18, ' Private', 54440, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(18, ' Private', 236069, ' 10th', 6, 'Single', ' Other-service', ' Own-child', ' Black', ' Male', 0, 0, 10, ' United-States', ' <=50K')
(18, ' Private', 110142, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 30, ' United-States', ' <=50K')
(18, ' Private', 444607, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 25, ' United-States', ' <=50K')
(19, ' State-gov', 67217, ' Some-college', 10, 'Single', ' Other-service', ' Not-in-family', ' White', ' Male', 594, 0, 24, ' United-States', ' <=50K')
(19, ' Private', 184121, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(18, ' Private', 60981, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Female', 2176, 0, 35, ' United-States', ' <=50K')
(17, ' Private', 266134, ' 10th', 6, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 12, ' United-States', ' <=50K')
(19, ' Self-emp-not-inc', 137578, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 53, ' United-States', ' <=50K')
(17, ' Private', 317702, ' 9th', 5, 'Single', ' Other-service', ' Own-child', ' Black', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(18, ' Private', 88642, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Male', 0, 0, 15, ' United-States', ' <=50K')
(17, ' ?', 89870, ' 10th', 6, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(17, ' Private', 123335, ' 10th', 6, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 64112, ' 12th', 8, 'Single', ' Adm-clerical', ' Not-in-family', ' White', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 151801, ' 10th', 6, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 39, ' United-States', ' <=50K')
(19, ' Private', 378114, ' HS-grad', 9, ' Married-civ-spouse', ' Craft-repair', ' Husband', ' White', ' Male', 0, 0, 25, ' United-States', ' <=50K')
(19, ' ?', 185619, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(18, ' Private', 96445, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 24, ' United-States', ' <=50K')
(17, ' Private', 347322, ' 10th', 6, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 236879, ' Some-college', 10, 'Single', ' Exec-managerial', ' Own-child', ' White', ' Female', 0, 0, 35, ' United-States', ' <=50K')
(19, ' Private', 142219, ' Some-college', 10, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 30, ' United-States', ' <=50K')
(19, ' Private', 270551, ' HS-grad', 9, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(17, ' ?', 64785, ' 10th', 6, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(19, ' Private', 574271, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Male', 0, 0, 35, ' United-States', ' <=50K')
(18, ' Private', 184016, ' HS-grad', 9, ' Married-civ-spouse', ' Priv-house-serv', ' Not-in-family', ' White', ' Female', 3103, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 407759, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 236570, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 16, ' United-States', ' <=50K')
(19, ' ?', 141418, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 15, ' United-States', ' <=50K')
(19, ' Private', 306225, ' HS-grad', 9, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 25, ' United-States', ' <=50K')
(19, ' Private', 208506, ' Some-college', 10, 'Single', ' Exec-managerial', ' Own-child', ' White', ' Female', 0, 0, 28, ' United-States', ' <=50K')
(17, ' Self-emp-not-inc', 174120, ' 12th', 8, 'Single', ' Handlers-cleaners', ' Own-child', ' White', ' Male', 0, 0, 15, ' United-States', ' <=50K')
(18, ' ?', 344742, ' 10th', 6, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' ?', 60688, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 35, ' United-States', ' <=50K')
(18, ' Private', 322999, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(17, ' Private', 230789, ' 9th', 5, 'Single', ' Sales', ' Own-child', ' Black', ' Male', 0, 0, 22, ' United-States', ' <=50K')
(18, ' State-gov', 272918, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Own-child', ' Black', ' Male', 0, 0, 15, ' United-States', ' <=50K')
(19, ' Private', 439779, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Male', 0, 0, 15, ' United-States', ' <=50K')
(19, ' ?', 182609, ' HS-grad', 9, 'Single', ' ?', ' Own-child', ' Black', ' Female', 0, 0, 25, ' United-States', ' <=50K')
(19, ' ?', 195282, ' HS-grad', 9, 'Single', ' ?', ' Own-child', ' Black', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(18, ' ?', 91670, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' Asian-Pac-Islander', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 175081, ' 9th', 5, 'Single', ' Craft-repair', ' Other-relative', ' White', ' Male', 0, 0, 60, ' United-States', ' <=50K')
(18, ' Private', 106780, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 12, ' United-States', ' <=50K')
(19, ' Private', 389143, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(18, ' Private', 201871, ' 12th', 8, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(18, ' Private', 205218, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(18, ' Private', 77845, ' Some-college', 10, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Male', 0, 1602, 15, ' United-States', ' <=50K')
(19, ' Private', 162094, ' HS-grad', 9, 'Single', ' Machine-op-inspct', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(18, ' Private', 156950, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Male', 0, 0, 35, ' United-States', ' <=50K')
(19, ' Private', 85690, ' HS-grad', 9, 'Single', ' Machine-op-inspct', ' Unmarried', ' White', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(17, ' ?', 67808, ' 10th', 6, 'Single', ' ?', ' Own-child', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(19, ' Private', 95078, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Own-child', ' White', ' Female', 0, 0, 15, ' United-States', ' <=50K')
(19, ' ?', 278220, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' White', ' Female', 0, 1602, 40, ' United-States', ' <=50K')
(18, ' Self-emp-inc', 147612, ' HS-grad', 9, 'Single', ' Farming-fishing', ' Own-child', ' White', ' Female', 0, 0, 8, ' United-States', ' <=50K')
(19, ' Private', 32477, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 204389, ' HS-grad', 9, 'Single', ' Adm-clerical', ' Own-child', ' Other', ' Female', 0, 0, 25, ' Puerto-Rico', ' <=50K')
(19, ' Private', 201743, ' Some-college', 10, 'Single', ' Other-service', ' Own-child', ' White', ' Female', 0, 0, 15, ' United-States', ' <=50K')
(19, ' ?', 71592, ' Some-college', 10, 'Single', ' ?', ' Own-child', ' Asian-Pac-Islander', ' Female', 0, 0, 40, ' United-States', ' <=50K')
(18, ' Private', 192409, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 20, ' United-States', ' <=50K')
(19, ' Private', 197714, ' HS-grad', 9, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 35, ' United-States', ' <=50K')
(19, ' ?', 309284, ' Some-college', 10, 'Single', ' ?', ' Not-in-family', ' White', ' Male', 0, 0, 40, ' United-States', ' <=50K')
(17, ' Private', 160758, ' 10th', 6, 'Single', ' Sales', ' Other-relative', ' White', ' Male', 0, 0, 30, ' United-States', ' <=50K')
(17, ' Private', 101626, ' 9th', 5, 'Single', ' Machine-op-inspct', ' Own-child', ' White', ' Male', 0, 0, 20, ' United-States', ' <=50K')
(18, ' Local-gov', 55658, ' 10th', 6, 'Single', ' Other-service', ' Own-child', ' White', ' Male', 0, 0, 25, ' United-States', ' <=50K')
(18, ' Private', 199039, ' 12th', 8, 'Single', ' Sales', ' Own-child', ' White', ' Male', 594, 0, 14, ' United-States', ' <=50K')
(17, ' Private', 220562, ' 9th', 5, 'Single', ' Sales', ' Other-relative', ' Other', ' Female', 0, 0, 32, ' Mexico', ' <=50K')
(19, ' Private', 143857, ' Some-college', 10, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 35, ' United-States', ' <=50K')
(19, ' Private', 175083, ' HS-grad', 9, 'Single', ' Sales', ' Own-child', ' White', ' Female', 0, 0, 8, ' United-States', ' <=50K')

In [67]:
filter2 = engine.execute('''select age,sex from adult where marital_status=" Divorced"''')

for row in filter2:
    print (row)

(38, ' Male')
(43, ' Female')
(59, ' Female')
(39, ' Male')
(45, ' Male')
(44, ' Female')
(50, ' Male')
(47, ' Male')
(29, ' Male')
(28, ' Female')
(44, ' Female')
(53, ' Female')
(37, ' Female')
(28, ' Female')
(48, ' Female')
(39, ' Male')
(46, ' Female')
(43, ' Female')
(47, ' Female')
(52, ' Male')
(29, ' Male')
(44, ' Female')
(36, ' Female')
(43, ' Female')
(41, ' Female')
(53, ' Female')
(38, ' Female')
(36, ' Male')
(37, ' Female')
(35, ' Male')
(50, ' Female')
(60, ' Female')
(65, ' Female')
(41, ' Female')
(33, ' Female')
(38, ' Male')
(36, ' Female')
(30, ' Female')
(34, ' Female')
(60, ' Female')
(50, ' Male')
(31, ' Female')
(37, ' Female')
(38, ' Male')
(43, ' Female')
(36, ' Female')
(35, ' Male')
(30, ' Female')
(43, ' Male')
(57, ' Female')
(39, ' Female')
(46, ' Male')
(54, ' Male')
(46, ' Female')
(45, ' Female')
(34, ' Female')
(41, ' Female')
(33, ' Female')
(35, ' Male')
(34, ' Female')
(29, ' Male')
(45, ' Female')
(52, ' Male')
(67, ' Female')
(45, ' Female')
(46, ' Male')
(34, ' Female')
(41, ' Female')
(58, ' Female')
(39, ' Female')
(28, ' Male')
(24, ' Male')
(44, ' Male')
(74, ' Female')
(46, ' Male')
(33, ' Female')
(47, ' Male')
(36, ' Female')
(57, ' Male')
(52, ' Female')
(26, ' Male')
(31, ' Female')
(42, ' Female')
(48, ' Male')
(34, ' Female')
(46, ' Female')
(44, ' Female')
(36, ' Female')
(36, ' Female')
(55, ' Female')
(34, ' Male')
(47, ' Female')
(31, ' Male')
(23, ' Male')
(36, ' Female')
(42, ' Female')
(43, ' Male')
(31, ' Female')
(43, ' Male')
(25, ' Male')
(41, ' Female')
(43, ' Male')
(40, ' Female')
(26, ' Female')
(48, ' Male')
(38, ' Female')
(49, ' Female')
(29, ' Female')
(48, ' Female')
(47, ' Male')
(46, ' Female')
(37, ' Male')
(37, ' Male')
(38, ' Male')
(42, ' Male')
(31, ' Female')
(54, ' Female')
(40, ' Female')
(43, ' Male')
(44, ' Male')
(33, ' Male')
(32, ' Female')
(36, ' Female')
(34, ' Male')
(63, ' Female')
(47, ' Female')
(44, ' Male')
(45, ' Male')
(48, ' Male')
(51, ' Female')
(22, ' Male')
(34, ' Female')
(43, ' Female')
(28, ' Male')
(38, ' Male')
(41, ' Female')
(36, ' Female')
(19, ' Female')
(38, ' Male')
(34, ' Male')
(43, ' Female')
(34, ' Female')
(34, ' Female')
(45, ' Female')
(48, ' Female')
(41, ' Male')
(34, ' Female')
(42, ' Male')
(40, ' Female')
(33, ' Female')
(40, ' Male')
(51, ' Female')
(40, ' Female')
(51, ' Male')
(49, ' Female')
(37, ' Male')
(31, ' Female')
(33, ' Female')
(31, ' Male')
(50, ' Female')
(52, ' Female')
(49, ' Male')
(52, ' Female')
(44, ' Male')
(42, ' Female')
(51, ' Female')
(71, ' Female')
(47, ' Male')
(51, ' Female')
(49, ' Female')
(41, ' Female')
(32, ' Female')
(40, ' Male')
(59, ' Female')
(50, ' Female')
(42, ' Female')
(37, ' Male')
(59, ' Female')
(32, ' Male')
(41, ' Female')
(38, ' Male')
(25, ' Male')
(25, ' Male')
(40, ' Male')
(49, ' Female')
(38, ' Female')
(57, ' Female')
(37, ' Male')
(26, ' Female')
(35, ' Female')
(49, ' Male')
(44, ' Male')
(47, ' Female')
(30, ' Female')
(33, ' Male')
(37, ' Female')
(48, ' Female')
(50, ' Female')
(26, ' Female')
(44, ' Male')
(39, ' Male')
(51, ' Male')
(28, ' Male')
(57, ' Female')
(50, ' Male')
(58, ' Female')
(67, ' Female')
(27, ' Female')
(52, ' Female')
(59, ' Female')
(39, ' Female')
(43, ' Male')
(37, ' Female')
(53, ' Female')
(44, ' Male')
(37, ' Female')
(29, ' Female')
(22, ' Female')
(39, ' Female')
(42, ' Female')
(31, ' Female')
(38, ' Male')
(44, ' Male')
(29, ' Male')
(45, ' Male')
(38, ' Male')
(37, ' Female')
(60, ' Female')
(47, ' Male')
(41, ' Female')
(46, ' Female')
(40, ' Female')
(43, ' Male')
(52, ' Female')
(52, ' Male')
(48, ' Female')
(51, ' Male')
(37, ' Female')
(45, ' Female')
(42, ' Female')
(30, ' Male')
(28, ' Male')
(23, ' Male')
(36, ' Female')
(46, ' Male')
(30, ' Female')
(26, ' Male')
(45, ' Female')
(41, ' Male')
(43, ' Male')
(24, ' Female')
(57, ' Female')
(29, ' Female')
(39, ' Male')
(53, ' Female')
(50, ' Male')
(44, ' Male')
(51, ' Male')
(32, ' Male')
(35, ' Female')
(53, ' Male')
(47, ' Female')
(60, ' Female')
(34, ' Male')
(51, ' Female')
(42, ' Male')
(35, ' Male')
(56, ' Female')
(47, ' Female')
(30, ' Female')
(37, ' Male')
(45, ' Female')
(41, ' Female')
(42, ' Female')
(52, ' Female')
(31, ' Male')
(32, ' Male')
(64, ' Female')
(41, ' Male')
(46, ' Male')
(47, ' Male')
(39, ' Female')
(53, ' Female')
(43, ' Female')
(63, ' Female')
(58, ' Male')
(64, ' Female')
(39, ' Female')
(46, ' Female')
(31, ' Male')
(38, ' Male')
(46, ' Male')
(56, ' Female')
(31, ' Female')
(43, ' Male')
(26, ' Male')
(32, ' Male')
(32, ' Male')
(27, ' Female')
(34, ' Female')
(20, ' Female')
(42, ' Male')
(34, ' Male')
(36, ' Female')
(44, ' Male')
(54, ' Female')
(29, ' Female')
(46, ' Female')
(48, ' Female')
(37, ' Female')
(31, ' Male')
(46, ' Male')
(48, ' Female')
(46, ' Female')
(42, ' Male')
(55, ' Female')
(54, ' Female')
(36, ' Male')
(38, ' Male')
(52, ' Female')
(42, ' Male')
(43, ' Male')
(41, ' Female')
(38, ' Female')
(35, ' Female')
(59, ' Female')
(46, ' Male')
(48, ' Female')
(51, ' Female')
(50, ' Female')
(35, ' Female')
(37, ' Female')
(45, ' Female')
(24, ' Female')
(34, ' Male')
(42, ' Female')
(48, ' Female')
(40, ' Female')
(49, ' Male')
(18, ' Male')
(50, ' Male')
(40, ' Female')
(56, ' Male')
(40, ' Female')
(46, ' Female')
(39, ' Female')
(42, ' Male')
(51, ' Male')
(45, ' Female')
(49, ' Female')
(58, ' Female')
(42, ' Male')
(57, ' Female')
(47, ' Male')
(55, ' Male')
(34, ' Female')
(24, ' Female')
(32, ' Female')
(41, ' Female')
(27, ' Male')
(40, ' Male')
(43, ' Male')
(44, ' Male')
(55, ' Female')
(34, ' Male')
(34, ' Female')
(41, ' Female')
(22, ' Male')
(40, ' Male')
(28, ' Female')
(45, ' Female')
(30, ' Male')
(41, ' Female')
(45, ' Female')
(34, ' Female')
(22, ' Female')
(33, ' Female')
(38, ' Female')
(56, ' Male')
(52, ' Female')
(40, ' Female')
(35, ' Male')
(34, ' Male')
(29, ' Male')
(40, ' Female')
(28, ' Female')
(62, ' Male')
(37, ' Female')
(33, ' Female')
(37, ' Female')
(49, ' Male')
(40, ' Male')
(42, ' Female')
(54, ' Male')
(48, ' Female')
(40, ' Female')
(36, ' Male')
(34, ' Male')
(35, ' Female')
(44, ' Female')
(46, ' Female')
(45, ' Female')
(22, ' Female')
(54, ' Female')
(42, ' Female')
(37, ' Female')
(32, ' Female')
(43, ' Male')
(36, ' Male')
(33, ' Female')
(28, ' Male')
(47, ' Male')
(44, ' Male')
(52, ' Female')
(47, ' Male')
(31, ' Male')
(45, ' Female')
(58, ' Female')
(45, ' Female')
(43, ' Female')
(31, ' Female')
(37, ' Female')
(50, ' Male')
(58, ' Female')
(39, ' Female')
(32, ' Female')
(59, ' Female')
(34, ' Female')
(53, ' Female')
(57, ' Female')
(40, ' Female')
(40, ' Female')
(39, ' Male')
(53, ' Female')
(40, ' Female')
(59, ' Male')
(41, ' Male')
(49, ' Female')
(31, ' Male')
(43, ' Female')
(27, ' Female')
(40, ' Female')
(23, ' Male')
(52, ' Female')
(39, ' Female')
(62, ' Female')
(55, ' Female')
(47, ' Female')
(32, ' Female')
(39, ' Female')
(39, ' Female')
(67, ' Female')
(51, ' Male')
(30, ' Female')
(51, ' Male')
(34, ' Female')
(54, ' Female')
(25, ' Female')
(30, ' Female')
(37, ' Male')
(30, ' Female')
(41, ' Male')
(32, ' Female')
(31, ' Male')
(37, ' Female')
(31, ' Male')
(53, ' Female')
(48, ' Female')
(30, ' Male')
(36, ' Female')
(58, ' Male')
(34, ' Female')
(41, ' Male')
(30, ' Male')
(29, ' Female')
(32, ' Female')
(29, ' Female')
(39, ' Female')
(55, ' Female')
(51, ' Female')
(40, ' Female')
(63, ' Male')
(51, ' Female')
(47, ' Male')
(38, ' Female')
(46, ' Female')
(54, ' Female')
(49, ' Male')
(55, ' Female')
(29, ' Female')
(51, ' Female')
(48, ' Female')
(51, ' Male')
(36, ' Male')
(27, ' Female')
(26, ' Male')
(50, ' Male')
(57, ' Female')
(48, ' Female')
(52, ' Male')
(53, ' Female')
(46, ' Female')
(38, ' Male')
(42, ' Female')
(29, ' Female')
(42, ' Female')
(52, ' Female')
(43, ' Male')
(59, ' Male')
(36, ' Male')
(48, ' Male')
(50, ' Female')
(49, ' Male')
(52, ' Male')
(64, ' Female')
(59, ' Female')
(28, ' Male')
(37, ' Female')
(31, ' Female')
(26, ' Female')
(28, ' Female')
(35, ' Male')
(44, ' Female')
(57, ' Female')
(28, ' Male')
(31, ' Male')
(51, ' Female')
(58, ' Male')
(41, ' Female')
(33, ' Female')
(59, ' Female')
(28, ' Female')
(37, ' Female')
(33, ' Male')
(46, ' Male')
(43, ' Male')
(38, ' Female')
(54, ' Female')
(24, ' Female')
(38, ' Female')
(30, ' Male')
(52, ' Female')
(33, ' Male')
(46, ' Female')
(28, ' Male')
(46, ' Female')
(50, ' Female')
(30, ' Female')
(59, ' Female')
(64, ' Female')
(41, ' Male')
(35, ' Female')
(41, ' Male')
(32, ' Female')
(38, ' Female')
(38, ' Male')
(42, ' Male')
(43, ' Female')
(44, ' Female')
(46, ' Male')
(52, ' Female')
(46, ' Female')
(66, ' Female')
(33, ' Male')
(48, ' Female')
(35, ' Male')
(63, ' Male')
(40, ' Female')
(28, ' Male')
(50, ' Male')
(49, ' Female')
(52, ' Female')
(24, ' Female')
(38, ' Male')
(35, ' Male')
(43, ' Female')
(40, ' Male')
(40, ' Female')
(52, ' Male')
(56, ' Male')
(31, ' Male')
(26, ' Male')
(29, ' Female')
(37, ' Female')
(35, ' Female')
(43, ' Female')
(46, ' Female')
(37, ' Female')
(28, ' Female')
(63, ' Female')
(25, ' Female')
(33, ' Female')
(40, ' Male')
(33, ' Female')
(36, ' Female')
(48, ' Female')
(43, ' Female')
(39, ' Female')
(43, ' Female')
(36, ' Female')
(25, ' Male')
(66, ' Female')
(48, ' Female')
(35, ' Female')
(55, ' Female')
(33, ' Male')
(40, ' Female')
(26, ' Male')
(32, ' Male')
(39, ' Female')
(55, ' Female')
(43, ' Male')
(51, ' Male')
(62, ' Female')
(50, ' Female')
(54, ' Female')
(31, ' Male')
(65, ' Male')
(66, ' Female')
(44, ' Female')
(36, ' Male')
(40, ' Male')
(69, ' Female')
(56, ' Female')
(47, ' Female')
(47, ' Male')
(42, ' Female')
(81, ' Female')
(57, ' Male')
(68, ' Female')
(33, ' Female')
(47, ' Female')
(42, ' Male')
(35, ' Female')
(48, ' Male')
(44, ' Male')
(32, ' Male')
(60, ' Female')
(36, ' Female')
(45, ' Male')
(33, ' Male')
(47, ' Male')
(56, ' Male')
(44, ' Female')
(27, ' Female')
(25, ' Female')
(44, ' Female')
(42, ' Female')
(35, ' Female')
(40, ' Male')
(35, ' Female')
(38, ' Male')
(33, ' Female')
(39, ' Female')
(40, ' Male')
(57, ' Female')
(51, ' Female')
(41, ' Female')
(54, ' Female')
(67, ' Female')
(41, ' Female')
(36, ' Female')
(43, ' Male')
(43, ' Female')
(42, ' Female')
(53, ' Female')
(61, ' Female')
(52, ' Male')
(48, ' Male')
(30, ' Female')
(35, ' Female')
(42, ' Female')
(38, ' Male')
(23, ' Female')
(40, ' Male')
(77, ' Male')
(41, ' Male')
(42, ' Male')
(40, ' Female')
(40, ' Female')
(49, ' Female')
(47, ' Female')
(28, ' Female')
(31, ' Female')
(49, ' Female')
(61, ' Male')
(35, ' Male')
(31, ' Female')
(35, ' Male')
(32, ' Female')
(35, ' Female')
(60, ' Female')
(50, ' Female')
(33, ' Female')
(53, ' Female')
(44, ' Female')
(56, ' Female')
(33, ' Male')
(32, ' Male')
(45, ' Female')
(47, ' Female')
(49, ' Male')
(44, ' Male')
(37, ' Male')
(35, ' Male')
(41, ' Female')
(55, ' Female')
(43, ' Male')
(43, ' Female')
(56, ' Male')
(60, ' Male')
(55, ' Female')
(43, ' Female')
(42, ' Female')
(26, ' Female')
(33, ' Male')
(30, ' Male')
(27, ' Female')
(44, ' Male')
(55, ' Female')
(35, ' Female')
(44, ' Female')
(36, ' Female')
(35, ' Female')
(47, ' Male')
(48, ' Female')
(34, ' Female')
(46, ' Male')
(45, ' Male')
(53, ' Male')
(40, ' Female')
(38, ' Female')
(41, ' Female')
(59, ' Male')
(63, ' Female')
(30, ' Female')
(37, ' Female')
(40, ' Male')
(45, ' Male')
(46, ' Female')
(47, ' Female')
(46, ' Female')
(42, ' Female')
(37, ' Female')
(41, ' Female')
(52, ' Female')
(27, ' Female')
(19, ' Female')
(42, ' Female')
(27, ' Male')
(39, ' Female')
(44, ' Male')
(49, ' Male')
(37, ' Male')
(30, ' Male')
(39, ' Male')
(48, ' Male')
(59, ' Male')
(42, ' Male')
(55, ' Male')
(57, ' Female')
(42, ' Male')
(44, ' Female')
(53, ' Male')
(45, ' Male')
(32, ' Female')
(44, ' Male')
(37, ' Female')
(43, ' Male')
(44, ' Female')
(35, ' Female')
(40, ' Male')
(44, ' Female')
(50, ' Male')
(31, ' Male')
(57, ' Male')
(56, ' Male')
(33, ' Male')
(43, ' Female')
(45, ' Male')
(42, ' Female')
(56, ' Male')
(35, ' Female')
(40, ' Female')
(47, ' Female')
(23, ' Male')
(34, ' Female')
(30, ' Female')
(31, ' Male')
(58, ' Female')
(38, ' Male')
(58, ' Female')
(51, ' Male')
(46, ' Male')
(57, ' Female')
(53, ' Male')
(55, ' Male')
(70, ' Female')
(56, ' Female')
(32, ' Female')
(33, ' Male')
(54, ' Male')
(24, ' Female')
(47, ' Female')
(42, ' Female')
(31, ' Female')
(38, ' Male')
(53, ' Male')
(24, ' Female')
(70, ' Female')
(32, ' Female')
(50, ' Male')
(40, ' Female')
(41, ' Female')
(34, ' Female')
(36, ' Male')
(42, ' Female')
(42, ' Female')
(37, ' Female')
(29, ' Male')
(37, ' Female')
(61, ' Male')
(51, ' Female')
(55, ' Female')
(40, ' Female')
(54, ' Male')
(37, ' Male')
(54, ' Female')
(51, ' Female')
(51, ' Female')
(47, ' Female')
(53, ' Female')
(39, ' Male')
(39, ' Male')
(36, ' Female')
(38, ' Male')
(33, ' Male')
(40, ' Female')
(51, ' Male')
(30, ' Female')
(49, ' Male')
(44, ' Male')
(75, ' Male')
(53, ' Female')
(25, ' Female')
(43, ' Female')
(34, ' Female')
(25, ' Female')
(45, ' Female')
(56, ' Male')
(38, ' Female')
(46, ' Female')
(43, ' Male')
(34, ' Male')
(31, ' Female')
(38, ' Female')
(38, ' Female')
(33, ' Male')
(34, ' Male')
(36, ' Female')
(42, ' Female')
(48, ' Male')
(41, ' Male')
(31, ' Male')
(39, ' Male')
(31, ' Male')
(54, ' Male')
(61, ' Female')
(44, ' Female')
(57, ' Female')
(30, ' Female')
(51, ' Female')
(39, ' Female')
(59, ' Female')
(35, ' Female')
(52, ' Female')
(40, ' Female')
(44, ' Male')
(22, ' Male')
(44, ' Male')
(33, ' Female')
(45, ' Female')
(39, ' Female')
(36, ' Male')
(45, ' Female')
(22, ' Female')
(49, ' Female')
(34, ' Female')
(40, ' Female')
(67, ' Female')
(48, ' Female')
(55, ' Female')
(63, ' Female')
(60, ' Female')
(46, ' Female')
(47, ' Male')
(27, ' Male')
(56, ' Female')
(47, ' Female')
(36, ' Female')
(40, ' Female')
(32, ' Male')
(34, ' Female')
(41, ' Male')
(38, ' Female')
(47, ' Female')
(49, ' Female')
(37, ' Female')
(41, ' Female')
(50, ' Female')
(38, ' Female')
(46, ' Male')
(42, ' Female')
(45, ' Female')
(45, ' Female')
(46, ' Male')
(37, ' Female')
(46, ' Female')
(36, ' Female')
(33, ' Male')
(47, ' Female')
(52, ' Female')
(36, ' Male')
(45, ' Male')
(23, ' Male')
(32, ' Male')
(52, ' Male')
(27, ' Female')
(52, ' Female')
(42, ' Male')
(41, ' Female')
(44, ' Male')
(48, ' Female')
(39, ' Male')
(32, ' Male')
(30, ' Male')
(41, ' Female')
(45, ' Female')
(40, ' Male')
(36, ' Male')
(49, ' Female')
(38, ' Male')
(41, ' Male')
(64, ' Female')
(24, ' Female')
(37, ' Male')
(35, ' Male')
(40, ' Female')
(46, ' Female')
(48, ' Male')
(36, ' Male')
(37, ' Male')
(44, ' Male')
(42, ' Male')
(41, ' Female')
(23, ' Female')
(39, ' Female')
(32, ' Male')
(50, ' Male')
(49, ' Female')
(55, ' Female')
(48, ' Female')
(46, ' Female')
(37, ' Female')
(37, ' Female')
(33, ' Female')
(26, ' Female')
(31, ' Female')
(23, ' Female')
(35, ' Female')
(53, ' Male')
(22, ' Male')
(33, ' Female')
(33, ' Male')
(50, ' Male')
(40, ' Male')
(36, ' Female')
(41, ' Female')
(54, ' Female')
(34, ' Male')
(45, ' Female')
(36, ' Male')
(51, ' Male')
(40, ' Female')
(60, ' Female')
(46, ' Female')
(60, ' Female')
(61, ' Male')
(65, ' Female')
(40, ' Male')
(46, ' Female')
(35, ' Female')
(35, ' Female')
(31, ' Male')
(49, ' Female')
(47, ' Female')
(45, ' Female')
(45, ' Female')
(35, ' Female')
(47, ' Male')
(51, ' Female')
(44, ' Female')
(53, ' Male')
(54, ' Male')
(68, ' Female')
(56, ' Female')
(41, ' Female')
(43, ' Female')
(27, ' Female')
(39, ' Male')
(52, ' Male')
(28, ' Female')
(40, ' Female')
(62, ' Female')
(59, ' Male')
(42, ' Female')
(58, ' Male')
(29, ' Male')
(35, ' Female')
(41, ' Male')
(36, ' Female')
(37, ' Male')
(31, ' Male')
(81, ' Female')
(29, ' Female')
(52, ' Male')
(51, ' Female')
(50, ' Female')
(29, ' Male')
(47, ' Female')
(46, ' Female')
(48, ' Female')
(47, ' Male')
(50, ' Female')
(55, ' Female')
(35, ' Female')
(45, ' Female')
(48, ' Female')
(34, ' Female')
(47, ' Female')
(34, ' Female')
(29, ' Female')
(51, ' Female')
(64, ' Male')
(42, ' Female')
(33, ' Male')
(50, ' Male')
(28, ' Male')
(67, ' Male')
(31, ' Male')
(30, ' Male')
(34, ' Female')
(50, ' Female')
(29, ' Male')
(32, ' Male')
(25, ' Female')
(37, ' Female')
(45, ' Male')
(20, ' Female')
(42, ' Female')
(59, ' Female')
(52, ' Male')
(32, ' Female')
(31, ' Male')
(37, ' Male')
(43, ' Male')
(56, ' Male')
(31, ' Female')
(32, ' Female')
(65, ' Female')
(43, ' Female')
(41, ' Male')
(49, ' Female')
(40, ' Female')
(45, ' Female')
(56, ' Female')
(43, ' Female')
(40, ' Male')
(58, ' Female')
(46, ' Female')
(50, ' Male')
(58, ' Male')
(56, ' Female')
(59, ' Female')
(27, ' Female')
(31, ' Male')
(45, ' Female')
(35, ' Male')
(42, ' Female')
(45, ' Female')
(43, ' Female')
(29, ' Female')
(45, ' Male')

(28, ' Male')
(41, ' Female')
(43, ' Female')
(65, ' Female')
(43, ' Male')
(47, ' Female')
(49, ' Female')
(40, ' Male')
(37, ' Female')
(40, ' Male')
(66, ' Male')
(59, ' Male')
(30, ' Female')
(47, ' Female')
(40, ' Male')
(39, ' Female')
(49, ' Female')
(34, ' Female')
(29, ' Male')
(61, ' Female')
(34, ' Male')
(34, ' Male')
(35, ' Male')
(38, ' Male')
(35, ' Male')
(32, ' Male')
(43, ' Male')
(49, ' Female')
(38, ' Female')
(40, ' Female')
(27, ' Female')
(42, ' Female')
(32, ' Male')
(30, ' Male')
(59, ' Female')
(53, ' Female')
(37, ' Male')
(31, ' Female')
(44, ' Female')
(36, ' Male')
(37, ' Female')
(60, ' Male')
(35, ' Female')
(43, ' Female')
(61, ' Female')
(33, ' Female')
(58, ' Female')
(31, ' Male')
(45, ' Male')
(38, ' Male')
(48, ' Female')
(45, ' Female')
(70, ' Male')
(33, ' Female')
(29, ' Female')
(22, ' Female')
(23, ' Female')
(53, ' Male')
(26, ' Female')
(46, ' Male')
(30, ' Male')
(28, ' Male')
(54, ' Female')
(42, ' Male')
(39, ' Female')
(39, ' Female')
(56, ' Female')
(60, ' Female')
(37, ' Female')
(58, ' Female')
(43, ' Female')
(56, ' Male')
(40, ' Male')
(45, ' Male')
(36, ' Female')
(44, ' Male')
(23, ' Female')
(65, ' Female')
(38, ' Female')
(26, ' Female')
(26, ' Male')
(47, ' Male')
(30, ' Male')
(27, ' Male')
(49, ' Female')
(61, ' Male')
(55, ' Female')
(30, ' Female')
(36, ' Male')
(43, ' Male')
(51, ' Male')
(37, ' Male')
(37, ' Female')
(37, ' Male')
(55, ' Female')
(29, ' Female')
(56, ' Male')
(42, ' Male')
(68, ' Female')
(38, ' Male')
(28, ' Female')
(51, ' Male')
(49, ' Male')
(53, ' Male')
(36, ' Female')
(38, ' Female')
(52, ' Male')
(45, ' Female')
(39, ' Female')
(36, ' Female')
(46, ' Male')
(45, ' Female')
(47, ' Female')
(50, ' Male')
(25, ' Male')
(32, ' Male')
(46, ' Female')
(46, ' Female')
(51, ' Female')
(51, ' Male')
(50, ' Female')
(46, ' Male')
(36, ' Male')
(31, ' Male')
(25, ' Male')
(42, ' Male')
(30, ' Male')
(35, ' Female')
(33, ' Male')
(45, ' Female')
(50, ' Female')
(32, ' Male')
(46, ' Female')
(36, ' Female')
(40, ' Female')
(59, ' Male')
(40, ' Male')
(44, ' Male')
(47, ' Female')
(44, ' Male')
(33, ' Female')
(38, ' Female')
(40, ' Male')
(46, ' Female')
(58, ' Male')
(52, ' Female')
(39, ' Female')
(47, ' Female')
(27, ' Male')
(48, ' Male')
(47, ' Female')
(42, ' Male')
(34, ' Female')
(43, ' Female')
(39, ' Female')
(53, ' Female')
(47, ' Female')
(27, ' Male')
(63, ' Female')
(50, ' Male')
(58, ' Male')
(60, ' Male')
(32, ' Female')
(49, ' Male')
(53, ' Female')
(36, ' Male')
(47, ' Male')
(41, ' Male')
(20, ' Female')
(36, ' Male')
(30, ' Female')
(41, ' Male')
(47, ' Female')
(49, ' Female')
(46, ' Male')
(44, ' Female')
(36, ' Female')
(46, ' Female')
(43, ' Female')
(36, ' Female')
(36, ' Female')
(40, ' Female')
(67, ' Female')
(35, ' Male')
(63, ' Female')
(50, ' Male')
(48, ' Male')
(63, ' Male')
(55, ' Female')
(27, ' Male')
(58, ' Female')
(53, ' Female')
(43, ' Female')
(50, ' Male')
(26, ' Male')
(50, ' Male')
(53, ' Female')
(31, ' Female')
(30, ' Female')
(44, ' Male')
(33, ' Female')
(48, ' Female')
(48, ' Male')
(28, ' Female')
(43, ' Female')
(46, ' Female')
(37, ' Male')
(47, ' Male')
(55, ' Male')
(44, ' Female')
(39, ' Female')
(34, ' Female')
(24, ' Female')
(28, ' Male')
(58, ' Male')
(48, ' Male')
(38, ' Female')
(50, ' Female')
(49, ' Female')
(31, ' Female')
(33, ' Male')
(47, ' Male')
(35, ' Male')
(35, ' Male')
(29, ' Female')
(65, ' Male')
(49, ' Male')
(50, ' Female')
(31, ' Female')
(45, ' Male')
(31, ' Male')
(44, ' Female')
(27, ' Female')
(39, ' Female')
(45, ' Female')
(35, ' Male')
(45, ' Male')
(50, ' Female')
(39, ' Female')
(27, ' Female')
(52, ' Female')
(22, ' Male')
(30, ' Female')
(69, ' Female')
(35, ' Female')
(48, ' Male')
(46, ' Female')
(36, ' Female')
(35, ' Male')
(39, ' Male')
(44, ' Male')
(44, ' Female')
(35, ' Male')
(50, ' Female')
(41, ' Male')
(33, ' Male')
(50, ' Male')
(60, ' Female')
(43, ' Male')
(28, ' Male')
(51, ' Female')
(44, ' Male')
(51, ' Male')
(45, ' Female')
(39, ' Female')
(45, ' Female')
(27, ' Male')
(51, ' Male')
(58, ' Male')
(41, ' Female')
(31, ' Female')
(50, ' Female')
(63, ' Male')
(48, ' Male')
(24, ' Male')
(43, ' Male')
(26, ' Female')
(36, ' Female')
(41, ' Male')
(36, ' Female')
(30, ' Male')
(35, ' Male')
(39, ' Female')
(32, ' Female')
(48, ' Male')
(33, ' Female')
(51, ' Male')
(33, ' Female')
(41, ' Male')
(42, ' Male')
(32, ' Female')
(50, ' Male')
(46, ' Female')
(58, ' Male')
(54, ' Female')
(40, ' Male')
(44, ' Female')
(36, ' Male')
(61, ' Female')
(42, ' Female')
(43, ' Female')
(28, ' Female')
(55, ' Female')
(34, ' Male')
(43, ' Female')
(54, ' Female')
(65, ' Male')
(37, ' Male')
(29, ' Male')
(47, ' Female')
(35, ' Female')
(38, ' Female')
(23, ' Male')
(57, ' Female')
(34, ' Male')
(42, ' Female')
(51, ' Male')
(28, ' Female')
(46, ' Female')
(33, ' Female')
(48, ' Male')
(30, ' Male')
(64, ' Female')
(40, ' Female')
(28, ' Male')
(29, ' Female')
(26, ' Female')
(38, ' Female')
(31, ' Male')
(29, ' Male')
(50, ' Female')
(33, ' Male')
(37, ' Female')
(45, ' Male')
(32, ' Male')
(49, ' Male')
(45, ' Male')
(43, ' Female')
(43, ' Female')
(45, ' Male')
(39, ' Female')
(49, ' Female')
(45, ' Female')
(28, ' Female')
(41, ' Male')
(57, ' Male')
(47, ' Male')
(50, ' Male')
(40, ' Male')
(55, ' Female')
(42, ' Female')
(48, ' Female')
(48, ' Female')
(50, ' Female')
(44, ' Male')
(65, ' Female')
(51, ' Female')
(54, ' Female')
(60, ' Male')
(58, ' Male')
(35, ' Female')
(32, ' Female')
(37, ' Male')
(36, ' Female')
(46, ' Female')
(32, ' Female')
(70, ' Male')
(40, ' Male')
(58, ' Male')
(38, ' Female')
(62, ' Male')
(55, ' Female')
(50, ' Female')
(60, ' Male')
(60, ' Female')
(32, ' Female')
(37, ' Male')
(53, ' Male')
(41, ' Male')
(51, ' Female')
(63, ' Female')
(48, ' Female')
(30, ' Female')
(41, ' Male')
(22, ' Female')
(33, ' Female')
(38, ' Female')
(24, ' Female')
(31, ' Female')
(29, ' Male')
(33, ' Female')
(54, ' Male')
(39, ' Male')
(31, ' Female')
(54, ' Male')
(54, ' Female')
(39, ' Male')
(50, ' Male')
(36, ' Female')
(43, ' Female')
(69, ' Male')
(39, ' Male')
(43, ' Female')
(42, ' Female')
(37, ' Female')
(30, ' Male')
(46, ' Male')
(57, ' Male')
(37, ' Male')
(39, ' Female')
(50, ' Male')
(53, ' Male')
(45, ' Female')
(38, ' Male')
(50, ' Female')
(41, ' Female')
(35, ' Female')
(71, ' Female')
(57, ' Female')
(39, ' Male')
(37, ' Female')
(28, ' Male')
(42, ' Male')
(47, ' Male')
(29, ' Female')
(49, ' Male')
(32, ' Female')
(37, ' Female')
(38, ' Male')
(44, ' Male')
(25, ' Female')
(45, ' Female')
(49, ' Male')
(24, ' Female')
(30, ' Female')
(47, ' Female')
(41, ' Female')
(49, ' Female')
(44, ' Female')
(45, ' Female')
(56, ' Male')
(38, ' Female')
(35, ' Female')
(36, ' Female')
(24, ' Male')
(35, ' Female')
(40, ' Female')
(36, ' Male')
(37, ' Female')
(59, ' Male')
(35, ' Male')
(45, ' Female')
(45, ' Female')
(29, ' Female')
(39, ' Female')
(44, ' Female')
(34, ' Male')
(43, ' Female')
(32, ' Male')
(34, ' Female')
(54, ' Male')
(42, ' Female')
(30, ' Female')
(39, ' Female')
(43, ' Female')
(35, ' Male')
(48, ' Male')
(27, ' Female')
(46, ' Female')
(76, ' Female')
(25, ' Female')
(41, ' Male')
(42, ' Female')
(43, ' Male')
(51, ' Female')
(41, ' Female')
(67, ' Female')
(40, ' Female')
(39, ' Female')
(39, ' Male')
(54, ' Female')
(36, ' Male')
(53, ' Female')
(55, ' Female')
(36, ' Male')
(37, ' Female')
(61, ' Female')
(36, ' Female')
(39, ' Female')
(39, ' Female')
(32, ' Female')
(29, ' Female')
(45, ' Female')
(35, ' Female')
(53, ' Male')
(38, ' Female')
(47, ' Female')
(34, ' Female')
(60, ' Female')
(33, ' Male')
(44, ' Male')
(26, ' Female')
(45, ' Male')
(58, ' Female')
(50, ' Female')
(57, ' Female')
(40, ' Male')
(55, ' Female')
(76, ' Female')
(48, ' Female')
(35, ' Male')
(29, ' Female')
(30, ' Female')
(28, ' Female')
(45, ' Female')
(26, ' Female')
(52, ' Male')
(45, ' Female')
(57, ' Female')
(38, ' Female')
(63, ' Female')
(47, ' Male')
(36, ' Male')
(60, ' Female')
(39, ' Female')
(39, ' Female')
(35, ' Female')
(68, ' Male')
(43, ' Female')
(50, ' Female')
(55, ' Female')
(42, ' Female')
(30, ' Female')
(28, ' Female')
(34, ' Male')
(42, ' Female')
(49, ' Male')
(48, ' Female')
(24, ' Male')
(36, ' Female')
(45, ' Female')
(38, ' Female')
(34, ' Female')
(42, ' Female')
(43, ' Female')
(50, ' Female')
(48, ' Male')
(43, ' Female')
(35, ' Female')
(35, ' Male')
(30, ' Female')
(51, ' Male')
(44, ' Female')
(49, ' Male')
(28, ' Female')
(42, ' Female')
(63, ' Male')
(30, ' Male')
(45, ' Female')
(41, ' Male')
(70, ' Female')
(39, ' Female')
(40, ' Male')
(51, ' Female')
(22, ' Female')
(21, ' Female')
(47, ' Female')
(49, ' Male')
(58, ' Female')
(58, ' Female')
(49, ' Female')
(60, ' Female')
(55, ' Male')
(64, ' Male')
(43, ' Male')
(31, ' Female')
(38, ' Male')
(48, ' Male')
(41, ' Female')
(52, ' Female')
(51, ' Female')
(39, ' Male')
(48, ' Female')
(46, ' Female')
(26, ' Female')
(40, ' Male')
(38, ' Male')
(33, ' Female')
(57, ' Male')
(60, ' Female')
(46, ' Male')
(32, ' Female')
(36, ' Female')
(56, ' Male')
(56, ' Female')
(41, ' Male')
(57, ' Male')
(35, ' Female')
(27, ' Male')
(40, ' Female')
(65, ' Female')
(51, ' Female')
(52, ' Male')
(28, ' Female')
(60, ' Female')
(28, ' Male')
(37, ' Female')
(28, ' Female')
(27, ' Female')
(49, ' Female')
(56, ' Male')
(40, ' Male')
(45, ' Female')
(58, ' Female')
(53, ' Female')
(40, ' Male')
(51, ' Female')
(33, ' Male')
(50, ' Male')
(46, ' Female')
(41, ' Female')
(49, ' Female')
(47, ' Female')
(41, ' Female')
(32, ' Female')
(54, ' Male')
(32, ' Female')
(39, ' Female')
(29, ' Female')
(45, ' Female')
(43, ' Female')
(47, ' Female')
(46, ' Female')
(37, ' Female')
(39, ' Female')
(33, ' Male')
(44, ' Female')
(24, ' Female')
(29, ' Female')
(41, ' Male')
(38, ' Male')
(48, ' Female')
(39, ' Female')
(37, ' Male')
(35, ' Female')
(49, ' Male')
(34, ' Female')
(61, ' Female')
(42, ' Female')
(35, ' Male')
(40, ' Male')
(49, ' Male')
(31, ' Male')
(34, ' Female')
(42, ' Male')
(37, ' Female')
(49, ' Female')
(46, ' Female')
(37, ' Male')
(27, ' Female')
(29, ' Female')
(26, ' Female')
(57, ' Male')
(50, ' Female')
(47, ' Male')
(47, ' Female')
(38, ' Male')
(56, ' Male')
(45, ' Male')
(65, ' Female')
(75, ' Female')
(42, ' Female')
(58, ' Male')
(59, ' Female')
(47, ' Male')
(30, ' Male')
(51, ' Female')
(21, ' Male')
(47, ' Male')
(31, ' Female')
(52, ' Female')
(32, ' Male')
(35, ' Male')
(53, ' Female')
(29, ' Male')
(39, ' Female')
(49, ' Male')
(48, ' Female')
(45, ' Male')
(44, ' Female')
(39, ' Male')
(46, ' Female')
(40, ' Female')
(34, ' Female')
(33, ' Male')
(59, ' Female')
(56, ' Female')
(30, ' Male')
(31, ' Female')
(39, ' Female')
(39, ' Male')
(43, ' Female')
(24, ' Female')
(37, ' Female')
(40, ' Female')
(36, ' Female')
(47, ' Female')
(44, ' Female')
(59, ' Male')
(40, ' Female')
(24, ' Female')
(51, ' Female')
(31, ' Female')
(58, ' Male')
(27, ' Female')
(33, ' Female')
(44, ' Male')
(45, ' Female')
(58, ' Male')

(72, ' Female')
(37, ' Male')
(44, ' Female')
(33, ' Female')
(42, ' Female')
(48, ' Female')
(42, ' Female')
(39, ' Female')
(37, ' Male')
(47, ' Female')
(49, ' Female')
(61, ' Male')
(45, ' Male')
(46, ' Male')
(33, ' Female')
(48, ' Male')
(44, ' Male')
(45, ' Female')
(52, ' Male')
(42, ' Male')
(40, ' Female')
(34, ' Female')
(60, ' Female')
(31, ' Female')
(59, ' Female')
(35, ' Male')
(37, ' Male')
(30, ' Female')
(32, ' Male')
(33, ' Male')
(27, ' Female')
(38, ' Female')
(55, ' Female')
(66, ' Female')
(49, ' Female')
(34, ' Male')
(37, ' Female')
(55, ' Female')
(30, ' Male')
(49, ' Male')
(49, ' Male')
(62, ' Female')
(42, ' Female')
(43, ' Female')
(40, ' Male')
(37, ' Male')
(34, ' Female')
(34, ' Male')
(45, ' Female')
(65, ' Male')
(33, ' Female')
(41, ' Female')
(47, ' Female')
(37, ' Male')
(43, ' Male')
(64, ' Female')
(36, ' Female')
(46, ' Female')
(43, ' Male')
(64, ' Male')
(46, ' Female')
(29, ' Female')
(48, ' Female')
(50, ' Female')
(37, ' Female')
(52, ' Male')
(41, ' Male')
(51, ' Male')
(25, ' Female')
(45, ' Female')
(25, ' Female')
(48, ' Female')
(34, ' Female')
(35, ' Female')
(64, ' Male')
(36, ' Male')
(41, ' Male')
(59, ' Male')
(39, ' Female')
(38, ' Female')
(31, ' Male')
(32, ' Male')
(44, ' Female')
(53, ' Female')
(50, ' Female')
(39, ' Female')
(29, ' Female')
(43, ' Female')
(33, ' Female')
(41, ' Male')
(34, ' Female')
(48, ' Female')
(30, ' Female')
(50, ' Female')
(47, ' Female')
(44, ' Male')
(38, ' Female')
(23, ' Female')
(67, ' Female')
(42, ' Female')
(31, ' Male')
(61, ' Female')
(49, ' Male')
(50, ' Female')
(49, ' Male')
(56, ' Female')
(40, ' Female')
(39, ' Female')
(53, ' Female')
(57, ' Female')
(39, ' Female')
(48, ' Male')
(33, ' Male')
(34, ' Male')
(55, ' Female')
(43, ' Female')
(46, ' Female')
(36, ' Male')
(26, ' Female')
(70, ' Female')
(26, ' Male')
(36, ' Male')
(48, ' Male')
(28, ' Female')
(50, ' Female')
(33, ' Female')
(45, ' Female')
(65, ' Male')
(31, ' Female')
(32, ' Male')
(56, ' Female')
(35, ' Female')
(22, ' Male')
(66, ' Female')
(50, ' Female')
(42, ' Female')
(36, ' Male')
(62, ' Female')
(31, ' Male')
(49, ' Female')
(35, ' Female')
(46, ' Female')
(37, ' Male')
(52, ' Female')
(31, ' Female')
(29, ' Female')
(53, ' Female')
(62, ' Male')
(44, ' Male')
(44, ' Male')
(49, ' Male')
(53, ' Male')
(47, ' Female')
(54, ' Male')
(45, ' Female')
(32, ' Male')
(38, ' Male')
(38, ' Male')
(35, ' Male')
(32, ' Male')
(31, ' Female')
(42, ' Female')
(42, ' Male')
(40, ' Male')
(39, ' Male')
(44, ' Male')
(53, ' Female')
(60, ' Female')
(58, ' Female')
(42, ' Female')
(54, ' Female')
(54, ' Female')
(39, ' Male')
(53, ' Female')
(41, ' Male')
(55, ' Male')
(45, ' Female')
(44, ' Male')
(26, ' Male')
(40, ' Male')
(28, ' Female')
(51, ' Female')
(31, ' Female')
(29, ' Female')
(33, ' Male')
(59, ' Female')
(67, ' Male')
(26, ' Male')
(44, ' Male')
(64, ' Female')
(56, ' Male')
(38, ' Female')
(66, ' Male')
(31, ' Male')
(39, ' Female')
(49, ' Male')
(36, ' Female')
(62, ' Female')
(43, ' Female')
(29, ' Female')
(48, ' Male')
(34, ' Female')
(33, ' Female')
(50, ' Female')
(60, ' Male')
(32, ' Female')
(31, ' Female')
(58, ' Female')
(40, ' Male')
(32, ' Female')
(46, ' Female')
(36, ' Female')
(29, ' Female')
(39, ' Male')
(33, ' Male')
(40, ' Male')
(68, ' Female')
(52, ' Male')
(52, ' Male')
(60, ' Male')
(38, ' Female')
(44, ' Female')
(46, ' Male')
(56, ' Male')
(56, ' Male')
(27, ' Male')
(46, ' Female')
(36, ' Male')
(44, ' Male')
(45, ' Female')
(53, ' Male')
(59, ' Male')
(45, ' Female')
(43, ' Female')
(53, ' Male')
(44, ' Male')
(49, ' Female')
(34, ' Male')
(45, ' Male')
(55, ' Male')
(49, ' Female')
(51, ' Female')
(59, ' Male')
(53, ' Male')
(43, ' Female')
(49, ' Male')
(32, ' Male')
(45, ' Male')
(34, ' Male')
(26, ' Male')
(58, ' Male')
(54, ' Female')
(58, ' Female')
(63, ' Male')
(67, ' Female')
(55, ' Female')
(39, ' Female')
(41, ' Male')
(44, ' Female')
(38, ' Female')
(50, ' Female')
(47, ' Female')
(64, ' Male')
(39, ' Female')
(57, ' Male')
(41, ' Male')
(48, ' Female')
(42, ' Male')
(58, ' Female')
(39, ' Female')
(41, ' Male')
(44, ' Female')
(44, ' Male')
(40, ' Male')
(54, ' Male')
(43, ' Female')
(45, ' Female')
(40, ' Male')
(58, ' Male')
(39, ' Male')
(27, ' Male')
(30, ' Female')
(63, ' Male')
(47, ' Male')
(41, ' Female')
(40, ' Female')
(50, ' Female')
(39, ' Female')
(40, ' Male')
(56, ' Female')
(57, ' Female')
(41, ' Male')
(28, ' Male')
(36, ' Male')
(30, ' Male')
(33, ' Male')
(39, ' Male')
(45, ' Female')
(34, ' Male')
(44, ' Male')
(34, ' Male')
(33, ' Female')
(52, ' Female')
(58, ' Female')
(39, ' Female')
(53, ' Male')
(43, ' Male')
(38, ' Female')
(42, ' Female')
(53, ' Male')
(54, ' Male')
(33, ' Male')
(45, ' Female')
(35, ' Female')
(32, ' Female')
(47, ' Female')
(32, ' Female')
(44, ' Female')
(55, ' Female')
(59, ' Female')
(53, ' Female')
(52, ' Female')
(44, ' Female')
(49, ' Female')
(46, ' Female')
(52, ' Female')
(42, ' Female')
(51, ' Female')
(52, ' Female')
(40, ' Female')
(45, ' Male')
(51, ' Female')
(42, ' Female')
(34, ' Male')
(28, ' Female')
(45, ' Female')
(40, ' Male')
(34, ' Male')
(30, ' Female')
(51, ' Male')
(53, ' Male')
(53, ' Female')
(42, ' Male')
(33, ' Female')
(44, ' Female')
(49, ' Female')
(31, ' Female')
(33, ' Male')
(46, ' Female')
(29, ' Male')
(61, ' Male')
(59, ' Male')
(36, ' Male')
(43, ' Female')
(41, ' Male')
(35, ' Female')
(36, ' Female')
(32, ' Female')
(45, ' Female')
(51, ' Female')
(33, ' Male')
(36, ' Female')
(35, ' Female')
(44, ' Male')
(38, ' Female')
(49, ' Female')
(27, ' Female')
(38, ' Female')
(28, ' Female')
(49, ' Male')
(42, ' Male')
(35, ' Female')
(48, ' Male')
(53, ' Female')
(37, ' Male')
(49, ' Female')
(33, ' Male')
(50, ' Male')
(52, ' Male')
(50, ' Female')
(42, ' Male')
(55, ' Female')
(25, ' Female')
(42, ' Male')
(40, ' Male')
(36, ' Male')
(36, ' Male')
(56, ' Female')
(45, ' Male')
(45, ' Female')
(30, ' Female')
(45, ' Male')
(35, ' Female')
(45, ' Female')
(46, ' Female')
(44, ' Female')
(46, ' Female')
(51, ' Male')
(48, ' Female')
(45, ' Female')
(49, ' Female')
(36, ' Female')
(20, ' Female')
(43, ' Male')
(44, ' Female')
(45, ' Male')
(51, ' Male')
(37, ' Female')
(58, ' Female')
(30, ' Male')
(44, ' Female')
(33, ' Female')
(58, ' Male')
(41, ' Male')
(41, ' Male')
(25, ' Female')
(57, ' Female')
(30, ' Female')
(39, ' Male')
(54, ' Male')
(63, ' Female')
(64, ' Male')
(40, ' Female')
(29, ' Male')
(44, ' Female')
(41, ' Female')
(55, ' Female')
(53, ' Female')
(49, ' Male')
(19, ' Female')
(38, ' Female')
(41, ' Female')
(45, ' Female')
(35, ' Male')
(40, ' Female')
(62, ' Female')
(59, ' Female')
(57, ' Female')
(41, ' Male')
(43, ' Male')
(43, ' Male')
(32, ' Male')
(34, ' Female')
(39, ' Female')
(39, ' Male')
(46, ' Female')
(32, ' Female')
(46, ' Male')
(36, ' Male')
(50, ' Female')
(41, ' Male')
(53, ' Female')
(40, ' Male')
(38, ' Female')
(43, ' Male')
(47, ' Male')
(46, ' Female')
(34, ' Female')
(46, ' Female')
(44, ' Female')
(45, ' Female')
(49, ' Female')
(49, ' Female')
(42, ' Female')
(36, ' Female')
(55, ' Female')
(55, ' Female')
(51, ' Male')
(35, ' Male')
(44, ' Female')
(43, ' Male')
(51, ' Female')
(40, ' Male')
(43, ' Female')
(59, ' Female')
(46, ' Female')
(31, ' Female')
(36, ' Female')
(38, ' Male')
(50, ' Female')
(49, ' Female')
(43, ' Female')
(35, ' Male')
(36, ' Female')
(42, ' Male')
(48, ' Female')
(23, ' Male')
(26, ' Female')
(36, ' Male')
(42, ' Female')
(60, ' Female')
(49, ' Female')
(38, ' Female')
(58, ' Female')
(55, ' Female')
(39, ' Female')
(38, ' Female')
(25, ' Female')
(39, ' Female')
(40, ' Female')
(41, ' Male')
(49, ' Female')
(55, ' Female')
(52, ' Male')
(58, ' Female')
(41, ' Male')
(32, ' Male')
(48, ' Male')
(48, ' Female')
(35, ' Male')
(49, ' Male')
(56, ' Female')
(26, ' Female')
(36, ' Female')
(41, ' Female')
(50, ' Female')
(34, ' Male')
(37, ' Male')
(36, ' Female')
(33, ' Male')
(54, ' Female')
(51, ' Male')
(44, ' Female')
(45, ' Female')
(44, ' Female')
(31, ' Female')
(40, ' Female')
(42, ' Male')
(41, ' Female')
(41, ' Male')
(51, ' Female')
(36, ' Male')
(40, ' Female')
(46, ' Female')
(44, ' Male')
(36, ' Male')
(44, ' Female')
(52, ' Female')
(20, ' Female')
(36, ' Female')
(30, ' Male')
(51, ' Male')
(57, ' Female')
(35, ' Female')
(59, ' Female')
(36, ' Female')
(67, ' Male')
(36, ' Male')
(32, ' Female')
(48, ' Female')
(45, ' Female')
(37, ' Female')
(29, ' Male')
(42, ' Female')
(57, ' Female')
(50, ' Male')
(37, ' Male')
(55, ' Male')
(39, ' Female')
(27, ' Female')
(43, ' Male')
(28, ' Female')
(26, ' Male')
(39, ' Female')
(43, ' Male')
(43, ' Female')
(40, ' Female')
(50, ' Male')
(74, ' Male')
(32, ' Female')
(29, ' Male')
(39, ' Male')
(40, ' Female')
(45, ' Male')
(47, ' Female')
(32, ' Female')
(34, ' Male')
(58, ' Female')
(23, ' Male')
(29, ' Female')
(61, ' Male')
(51, ' Female')
(50, ' Female')
(65, ' Female')
(64, ' Female')
(32, ' Female')
(34, ' Female')
(37, ' Male')
(60, ' Female')
(47, ' Male')
(30, ' Female')
(38, ' Male')
(30, ' Male')
(49, ' Female')
(52, ' Male')
(36, ' Female')
(37, ' Female')
(48, ' Male')
(58, ' Male')
(33, ' Female')
(31, ' Male')
(35, ' Male')
(41, ' Female')
(36, ' Female')
(34, ' Male')
(64, ' Male')
(47, ' Male')
(44, ' Male')
(32, ' Female')
(58, ' Female')
(36, ' Female')
(46, ' Female')
(43, ' Female')
(35, ' Female')
(46, ' Female')
(41, ' Female')
(52, ' Female')
(41, ' Male')
(44, ' Female')
(46, ' Male')
(45, ' Female')
(26, ' Female')
(47, ' Female')
(44, ' Male')
(25, ' Female')
(36, ' Male')
(47, ' Male')
(25, ' Female')
(53, ' Female')
(41, ' Male')
(35, ' Female')
(46, ' Female')
(48, ' Female')
(48, ' Male')
(55, ' Female')
(50, ' Female')
(46, ' Female')
(45, ' Female')
(44, ' Male')
(44, ' Female')
(52, ' Female')
(31, ' Female')
(45, ' Female')
(37, ' Female')
(44, ' Male')
(45, ' Female')
(40, ' Female')
(24, ' Female')
(55, ' Female')
(46, ' Female')
(58, ' Male')
(35, ' Male')
(49, ' Female')
(44, ' Female')
(38, ' Female')
(42, ' Female')
(43, ' Male')
(53, ' Female')
(58, ' Female')
(41, ' Female')
(44, ' Female')
(40, ' Male')
(51, ' Female')
(73, ' Female')
(44, ' Female')
(42, ' Female')
(42, ' Male')
(59, ' Female')
(47, ' Female')
(36, ' Male')
(53, ' Female')
(37, ' Female')
(41, ' Male')
(40, ' Female')
(52, ' Female')
(83, ' Male')
(35, ' Female')
(45, ' Male')
(90, ' Female')
(57, ' Female')
(35, ' Male')
(40, ' Female')
(46, ' Male')
(45, ' Female')
(50, ' Female')
(56, ' Female')
(36, ' Female')
(45, ' Female')
(53, ' Female')
(32, ' Male')
(49, ' Female')
(41, ' Female')
(32, ' Female')
(33, ' Female')
(30, ' Female')
(64, ' Female')
(49, ' Male')
(35, ' Male')
(68, ' Female')
(60, ' Male')
(48, ' Male')
(62, ' Male')
(60, ' Female')
(39, ' Female')
(45, ' Female')
(48, ' Male')
(44, ' Male')
(37, ' Female')
(46, ' Female')
(39, ' Male')
(30, ' Female')
(43, ' Female')
(26, ' Female')
(48, ' Male')
(41, ' Female')
(49, ' Male')
(36, ' Male')
(38, ' Female')
(43, ' Female')
(63, ' Female')
(41, ' Female')
(36, ' Male')
(32, ' Female')
(50, ' Male')
(37, ' Male')
(54, ' Female')
(51, ' Female')
(38, ' Female')
(43, ' Female')
(28, ' Male')
(43, ' Female')
(49, ' Female')
(36, ' Male')
(44, ' Male')
(40, ' Female')
(55, ' Male')
(51, ' Female')
(44, ' Male')
(40, ' Male')
(43, ' Female')
(48, ' Female')
(36, ' Female')
(30, ' Female')
(52, ' Male')
(46, ' Female')
(41, ' Female')
(43, ' Female')
(30, ' Female')
(43, ' Female')
(54, ' Male')
(60, ' Female')
(52, ' Female')
(48, ' Male')
(23, ' Female')
(40, ' Female')
(35, ' Male')
(47, ' Male')
(50, ' Male')
(37, ' Female')
(42, ' Male')
(61, ' Male')
(45, ' Male')
(60, ' Female')
(37, ' Male')
(47, ' Male')
(43, ' Female')
(58, ' Female')
(39, ' Female')
(58, ' Female')
(57, ' Female')
(33, ' Male')
(32, ' Male')
(46, ' Male')
(31, ' Male')
(46, ' Female')
(70, ' Male')
(41, ' Female')
(36, ' Male')
(35, ' Female')
(55, ' Male')

(39, ' Male')
(47, ' Female')
(50, ' Male')
(67, ' Female')
(34, ' Female')
(55, ' Male')
(23, ' Female')
(36, ' Female')
(43, ' Female')
(40, ' Female')
(42, ' Female')
(54, ' Male')
(35, ' Female')
(42, ' Female')
(46, ' Male')
(43, ' Female')
(39, ' Female')
(52, ' Male')
(43, ' Male')
(52, ' Female')
(44, ' Male')
(37, ' Male')
(36, ' Male')
(26, ' Female')
(38, ' Female')
(41, ' Female')
(23, ' Female')
(36, ' Male')
(46, ' Male')
(54, ' Male')
(37, ' Female')
(54, ' Female')
(25, ' Female')
(36, ' Female')
(40, ' Female')
(53, ' Male')
(45, ' Male')
(24, ' Male')
(37, ' Female')
(49, ' Female')
(40, ' Female')
(54, ' Male')
(40, ' Female')
(43, ' Female')
(41, ' Female')
(39, ' Female')
(42, ' Female')
(26, ' Male')
(43, ' Female')
(39, ' Male')
(44, ' Female')
(46, ' Female')
(40, ' Female')
(47, ' Female')
(41, ' Female')
(65, ' Male')
(55, ' Male')
(66, ' Female')
(54, ' Male')
(27, ' Female')
(50, ' Female')
(51, ' Female')
(41, ' Female')
(40, ' Male')
(42, ' Female')
(38, ' Male')
(41, ' Female')
(30, ' Female')
(49, ' Female')
(70, ' Male')
(41, ' Female')
(42, ' Male')
(28, ' Male')
(46, ' Male')
(44, ' Male')
(32, ' Female')
(47, ' Female')
(55, ' Female')
(30, ' Female')
(43, ' Male')
(46, ' Male')
(52, ' Female')
(49, ' Female')
(25, ' Male')
(43, ' Male')
(48, ' Female')
(43, ' Female')
(39, ' Female')
(54, ' Male')
(63, ' Male')
(47, ' Female')
(35, ' Male')
(54, ' Female')
(45, ' Male')
(46, ' Male')
(23, ' Male')
(45, ' Female')
(33, ' Female')
(51, ' Female')
(41, ' Female')
(44, ' Female')
(36, ' Female')
(27, ' Male')
(33, ' Female')
(57, ' Female')
(40, ' Female')
(33, ' Male')
(46, ' Male')
(40, ' Female')
(41, ' Male')
(55, ' Male')
(37, ' Male')
(49, ' Male')
(37, ' Female')
(43, ' Male')
(25, ' Male')
(45, ' Female')
(37, ' Female')
(51, ' Male')
(52, ' Female')
(36, ' Male')
(42, ' Male')
(61, ' Female')
(37, ' Male')
(51, ' Female')
(30, ' Male')
(26, ' Female')
(35, ' Female')
(52, ' Male')
(38, ' Female')
(57, ' Male')
(27, ' Female')
(47, ' Male')
(41, ' Female')
(52, ' Female')
(60, ' Female')
(61, ' Female')
(26, ' Male')
(32, ' Male')
(63, ' Male')
(31, ' Female')
(55, ' Female')
(41, ' Female')
(38, ' Female')
(36, ' Female')
(40, ' Female')
(36, ' Female')
(33, ' Male')
(38, ' Male')
(53, ' Male')
(42, ' Male')
(61, ' Female')
(44, ' Female')
(46, ' Female')
(49, ' Male')
(40, ' Female')
(43, ' Male')
(44, ' Male')
(52, ' Male')
(47, ' Female')
(37, ' Female')
(61, ' Male')
(32, ' Male')
(37, ' Male')
(38, ' Male')
(33, ' Female')
(57, ' Female')
(35, ' Male')
(39, ' Female')
(61, ' Female')
(47, ' Female')
(43, ' Male')
(40, ' Female')
(48, ' Male')
(49, ' Male')
(50, ' Female')
(62, ' Female')
(35, ' Male')
(29, ' Female')
(62, ' Male')
(51, ' Male')
(55, ' Male')
(31, ' Male')
(32, ' Male')
(31, ' Male')
(47, ' Female')
(42, ' Female')
(38, ' Male')
(47, ' Female')
(32, ' Female')
(39, ' Female')
(33, ' Male')
(28, ' Male')
(47, ' Male')
(33, ' Female')
(61, ' Male')
(37, ' Female')
(25, ' Female')
(37, ' Female')
(40, ' Male')
(32, ' Male')
(39, ' Female')
(34, ' Male')
(31, ' Female')
(41, ' Male')
(36, ' Male')
(55, ' Female')
(41, ' Male')
(35, ' Female')
(25, ' Female')
(35, ' Female')
(35, ' Female')
(55, ' Female')
(46, ' Female')
(47, ' Female')
(46, ' Female')
(57, ' Female')
(37, ' Male')
(38, ' Male')
(41, ' Male')
(52, ' Female')
(48, ' Male')
(48, ' Male')
(56, ' Female')
(47, ' Female')
(37, ' Female')
(30, ' Male')
(38, ' Female')
(45, ' Male')
(49, ' Female')
(35, ' Female')
(50, ' Male')
(41, ' Male')
(60, ' Male')
(67, ' Female')
(62, ' Female')
(37, ' Female')
(34, ' Female')
(44, ' Male')
(38, ' Female')
(45, ' Male')
(41, ' Male')
(50, ' Female')
(53, ' Female')
(34, ' Male')
(36, ' Male')
(33, ' Male')
(45, ' Male')
(35, ' Female')
(45, ' Male')
(49, ' Female')
(28, ' Female')
(37, ' Male')
(65, ' Female')
(42, ' Female')
(42, ' Female')
(39, ' Female')
(36, ' Female')
(57, ' Female')
(42, ' Female')
(42, ' Male')
(40, ' Male')
(67, ' Male')
(65, ' Female')
(50, ' Female')
(38, ' Female')
(34, ' Male')
(37, ' Male')
(28, ' Female')
(62, ' Female')
(48, ' Female')
(42, ' Male')
(30, ' Female')
(48, ' Male')
(70, ' Female')
(37, ' Male')
(34, ' Female')
(32, ' Female')
(32, ' Female')
(58, ' Male')
(52, ' Female')
(41, ' Female')
(59, ' Male')
(30, ' Female')
(47, ' Female')
(44, ' Female')
(26, ' Female')
(52, ' Male')
(46, ' Female')
(55, ' Male')
(33, ' Female')
(43, ' Female')
(39, ' Female')
(29, ' Male')
(49, ' Male')
(56, ' Female')
(57, ' Male')
(29, ' Female')
(28, ' Female')
(29, ' Female')
(42, ' Male')
(56, ' Male')
(53, ' Female')
(48, ' Male')
(38, ' Female')
(55, ' Male')
(52, ' Female')
(45, ' Male')
(46, ' Female')
(45, ' Male')
(50, ' Female')
(62, ' Female')
(67, ' Female')
(45, ' Male')
(69, ' Female')
(38, ' Female')
(39, ' Male')
(27, ' Female')
(33, ' Female')
(56, ' Female')
(44, ' Female')
(46, ' Female')
(46, ' Female')
(58, ' Male')
(49, ' Male')
(45, ' Male')
(34, ' Male')
(40, ' Female')
(45, ' Male')
(32, ' Female')
(48, ' Male')
(57, ' Female')
(40, ' Female')
(37, ' Male')
(39, ' Male')
(41, ' Male')
(49, ' Male')
(37, ' Male')
(51, ' Female')
(39, ' Female')
(42, ' Female')
(37, ' Male')
(47, ' Female')
(53, ' Male')
(42, ' Female')
(53, ' Male')
(58, ' Male')
(45, ' Female')
(39, ' Female')
(50, ' Male')
(51, ' Female')
(32, ' Female')
(56, ' Male')
(29, ' Male')
(47, ' Female')
(50, ' Male')
(53, ' Male')
(29, ' Female')
(36, ' Male')
(48, ' Female')
(51, ' Female')
(39, ' Male')
(53, ' Male')
(49, ' Female')
(43, ' Female')
(53, ' Female')
(39, ' Female')
(45, ' Male')
(33, ' Female')
(31, ' Female')
(53, ' Male')
(41, ' Female')
(40, ' Female')
(27, ' Female')
(30, ' Female')
(39, ' Male')
(48, ' Female')
(34, ' Male')
(33, ' Male')
(44, ' Female')
(30, ' Female')
(46, ' Female')
(35, ' Female')
(61, ' Female')
(57, ' Male')
(28, ' Female')
(60, ' Male')
(29, ' Male')
(50, ' Female')
(45, ' Female')
(88, ' Female')
(52, ' Male')
(51, ' Female')
(25, ' Female')
(37, ' Female')
(39, ' Female')
(40, ' Female')
(38, ' Male')
(46, ' Male')
(52, ' Female')
(31, ' Female')
(36, ' Female')
(33, ' Male')
(40, ' Male')
(56, ' Female')
(68, ' Female')
(45, ' Female')
(37, ' Male')
(32, ' Female')
(34, ' Female')
(47, ' Female')
(56, ' Female')
(46, ' Female')
(34, ' Male')
(20, ' Female')
(68, ' Male')
(48, ' Female')
(47, ' Female')
(46, ' Male')
(43, ' Male')
(40, ' Male')
(27, ' Female')
(28, ' Male')
(46, ' Male')
(44, ' Male')
(65, ' Female')
(41, ' Male')
(33, ' Female')
(59, ' Female')
(40, ' Female')
(35, ' Female')
(50, ' Male')
(40, ' Female')
(30, ' Female')
(39, ' Female')
(42, ' Male')
(51, ' Female')
(47, ' Female')
(49, ' Male')
(72, ' Male')
(47, ' Female')
(39, ' Female')
(36, ' Female')
(23, ' Female')
(25, ' Male')
(34, ' Female')
(35, ' Female')
(29, ' Female')
(44, ' Male')
(50, ' Female')
(38, ' Female')
(43, ' Male')
(33, ' Female')
(39, ' Male')
(45, ' Male')
(29, ' Male')
(32, ' Female')
(56, ' Female')
(35, ' Male')
(45, ' Male')
(46, ' Male')
(30, ' Male')
(41, ' Female')
(56, ' Female')
(45, ' Female')
(41, ' Female')
(54, ' Female')
(40, ' Male')
(59, ' Male')
(47, ' Female')
(39, ' Male')
(45, ' Male')
(40, ' Female')
(29, ' Male')
(47, ' Male')
(41, ' Male')
(71, ' Female')
(52, ' Female')
(54, ' Male')
(54, ' Female')
(31, ' Female')
(52, ' Female')
(53, ' Male')
(55, ' Female')
(47, ' Female')
(56, ' Female')
(32, ' Female')
(41, ' Female')
(42, ' Female')
(46, ' Female')
(34, ' Male')
(27, ' Female')
(48, ' Male')
(37, ' Female')
(35, ' Female')
(58, ' Female')
(25, ' Female')
(38, ' Female')
(63, ' Female')
(39, ' Female')
(50, ' Male')
(44, ' Female')
(62, ' Female')
(67, ' Female')
(43, ' Female')
(72, ' Male')
(48, ' Female')
(39, ' Female')
(67, ' Female')
(47, ' Female')
(48, ' Male')
(31, ' Female')
(29, ' Female')
(34, ' Female')
(40, ' Female')
(35, ' Male')
(44, ' Female')
(32, ' Male')
(38, ' Female')
(42, ' Female')
(37, ' Female')
(51, ' Female')
(47, ' Female')
(42, ' Male')
(40, ' Female')
(43, ' Female')
(46, ' Male')
(41, ' Female')
(42, ' Female')
(38, ' Male')
(47, ' Female')
(46, ' Female')
(39, ' Female')
(62, ' Male')
(41, ' Female')
(49, ' Male')
(40, ' Male')
(59, ' Male')
(51, ' Female')
(62, ' Male')
(49, ' Female')
(33, ' Female')
(42, ' Male')
(34, ' Female')
(40, ' Female')
(45, ' Female')
(41, ' Male')
(41, ' Female')
(46, ' Male')
(62, ' Male')
(34, ' Male')
(58, ' Female')
(32, ' Male')
(49, ' Female')
(29, ' Male')
(37, ' Female')
(36, ' Female')
(58, ' Female')
(39, ' Female')
(34, ' Female')
(39, ' Female')
(58, ' Female')
(37, ' Female')
(33, ' Female')
(19, ' Female')
(43, ' Male')
(31, ' Male')
(48, ' Female')
(32, ' Male')
(47, ' Male')
(41, ' Male')
(41, ' Male')
(38, ' Male')
(42, ' Female')
(40, ' Male')
(45, ' Female')
(57, ' Female')
(28, ' Female')
(43, ' Female')
(49, ' Female')
(30, ' Female')
(48, ' Female')
(55, ' Male')
(47, ' Female')
(33, ' Female')
(52, ' Male')
(26, ' Female')
(50, ' Female')
(35, ' Male')
(41, ' Female')
(39, ' Male')
(30, ' Male')
(45, ' Female')
(37, ' Female')
(48, ' Female')
(50, ' Female')
(50, ' Male')
(46, ' Female')
(37, ' Female')
(53, ' Female')
(46, ' Male')
(56, ' Female')
(52, ' Female')
(47, ' Female')
(40, ' Female')
(56, ' Male')
(24, ' Female')
(34, ' Male')
(24, ' Female')
(31, ' Female')
(27, ' Male')
(36, ' Female')
(29, ' Male')
(42, ' Female')
(44, ' Female')
(36, ' Female')
(52, ' Male')
(25, ' Male')
(49, ' Female')
(25, ' Female')
(28, ' Female')
(53, ' Female')
(34, ' Female')
(47, ' Female')
(51, ' Female')
(32, ' Male')
(59, ' Female')
(54, ' Male')
(49, ' Female')
(46, ' Male')
(41, ' Female')
(32, ' Male')
(44, ' Male')
(39, ' Female')
(31, ' Male')
(47, ' Female')
(26, ' Male')
(48, ' Male')
(46, ' Male')
(69, ' Female')
(39, ' Female')
(50, ' Female')
(45, ' Male')
(54, ' Female')
(58, ' Female')
(56, ' Female')
(39, ' Female')
(48, ' Female')
(52, ' Male')
(36, ' Male')
(55, ' Male')
(44, ' Female')
(35, ' Male')
(34, ' Female')
(57, ' Female')
(54, ' Male')
(28, ' Female')
(33, ' Female')
(46, ' Male')
(44, ' Female')
(30, ' Female')
(66, ' Female')
(33, ' Female')
(47, ' Female')
(26, ' Male')
(39, ' Female')
(74, ' Female')
(35, ' Male')
(35, ' Male')
(46, ' Female')
(50, ' Female')
(57, ' Male')
(56, ' Female')
(36, ' Male')
(35, ' Female')
(49, ' Female')
(41, ' Female')
(32, ' Male')
(48, ' Male')
(39, ' Male')
(55, ' Male')
(59, ' Female')
(51, ' Female')
(47, ' Female')
(42, ' Male')
(39, ' Female')
(32, ' Female')
(61, ' Female')
(43, ' Female')
(37, ' Male')
(36, ' Male')
(39, ' Male')
(46, ' Male')
(53, ' Female')
(51, ' Male')
(40, ' Male')
(61, ' Female')
(41, ' Female')
(39, ' Male')
(42, ' Female')
(42, ' Female')
(43, ' Male')
(40, ' Male')
(56, ' Female')
(32, ' Female')
(24, ' Male')
(46, ' Male')
(45, ' Male')
(47, ' Female')
(21, ' Male')
(57, ' Female')
(49, ' Female')
(48, ' Female')
(63, ' Female')
(41, ' Female')
(47, ' Female')
(36, ' Male')
(39, ' Male')
(54, ' Female')
(43, ' Female')
(52, ' Female')
(44, ' Female')
(45, ' Male')
(34, ' Male')
(40, ' Female')
(59, ' Male')
(32, ' Male')
(58, ' Female')
(32, ' Male')
(28, ' Male')
(30, ' Female')
(48, ' Male')
(37, ' Female')
(69, ' Male')
(40, ' Male')
(43, ' Male')
(33, ' Male')
(45, ' Female')
(49, ' Female')
(42, ' Male')
(59, ' Female')
(51, ' Female')
(28, ' Male')
(42, ' Female')
(41, ' Female')
(44, ' Male')
(56, ' Female')
(32, ' Female')
(33, ' Female')
(39, ' Male')
(47, ' Male')
(53, ' Female')
(27, ' Female')
(49, ' Female')
(31, ' Female')
(53, ' Female')
(32, ' Male')
(62, ' Female')
(51, ' Female')
(35, ' Female')
(31, ' Male')
(41, ' Female')
(53, ' Male')
(36, ' Female')
(48, ' Male')
(30, ' Female')
(29, ' Male')
(62, ' Male')
(37, ' Male')
(46, ' Female')
(57, ' Female')
(56, ' Male')
(45, ' Female')
(40, ' Female')
(53, ' Male')
(62, ' Male')
(37, ' Male')
(45, ' Male')
(31, ' Female')
(34, ' Female')
(42, ' Male')
(49, ' Female')
(53, ' Female')
(37, ' Male')
(30, ' Female')
(57, ' Female')
(49, ' Female')
(67, ' Male')
(35, ' Male')
(66, ' Female')

(37, ' Male')
(58, ' Female')
(50, ' Female')
(38, ' Male')
(43, ' Male')
(42, ' Female')
(35, ' Male')
(43, ' Female')
(55, ' Female')
(39, ' Male')
(32, ' Male')
(51, ' Male')
(35, ' Female')
(42, ' Female')
(32, ' Male')
(31, ' Female')
(59, ' Male')
(62, ' Female')
(44, ' Male')
(46, ' Male')
(44, ' Male')
(51, ' Female')
(38, ' Female')
(42, ' Male')
(51, ' Female')
(27, ' Male')
(39, ' Female')
(32, ' Female')
(29, ' Male')
(44, ' Female')
(49, ' Female')
(37, ' Female')
(29, ' Female')
(50, ' Male')
(40, ' Female')
(23, ' Female')
(55, ' Female')
(38, ' Male')
(53, ' Female')
(46, ' Female')
(28, ' Male')
(35, ' Female')
(36, ' Female')
(36, ' Male')
(43, ' Female')
(23, ' Female')
(51, ' Male')
(31, ' Male')
(34, ' Male')
(51, ' Female')
(42, ' Female')
(33, ' Female')
(46, ' Female')
(60, ' Male')
(68, ' Female')
(38, ' Female')
(28, ' Male')
(36, ' Male')
(59, ' Male')
(49, ' Female')
(49, ' Female')
(50, ' Male')
(45, ' Female')
(34, ' Female')
(37, ' Female')
(35, ' Female')
(44, ' Male')
(38, ' Female')
(62, ' Female')
(43, ' Female')
(58, ' Female')
(43, ' Male')
(31, ' Female')
(38, ' Male')
(39, ' Female')
(38, ' Female')
(49, ' Female')
(22, ' Female')
(60, ' Female')
(38, ' Male')
(46, ' Female')
(42, ' Female')
(43, ' Female')
(53, ' Female')
(53, ' Male')
(42, ' Male')
(55, ' Female')
(54, ' Female')
(45, ' Male')
(36, ' Female')
(41, ' Female')
(32, ' Female')
(33, ' Female')
(56, ' Male')
(65, ' Female')
(55, ' Male')
(58, ' Male')
(47, ' Female')
(43, ' Female')
(46, ' Female')
(31, ' Male')
(44, ' Male')
(30, ' Male')
(35, ' Male')
(54, ' Male')
(42, ' Male')
(33, ' Female')
(39, ' Male')
(58, ' Female')
(35, ' Male')
(48, ' Female')
(62, ' Female')
(35, ' Female')
(34, ' Male')
(44, ' Male')
(46, ' Male')
(32, ' Male')
(39, ' Male')
(38, ' Male')
(28, ' Male')
(34, ' Male')
(45, ' Male')
(61, ' Female')
(33, ' Male')
(44, ' Female')
(31, ' Female')
(40, ' Female')
(48, ' Female')
(34, ' Male')
(51, ' Female')
(60, ' Male')
(45, ' Female')
(32, ' Female')
(40, ' Female')
(51, ' Male')
(61, ' Female')
(60, ' Male')
(42, ' Female')
(45, ' Male')
(38, ' Female')
(38, ' Male')
(55, ' Female')
(27, ' Female')
(35, ' Female')
(56, ' Female')
(50, ' Female')
(41, ' Female')
(47, ' Female')
(40, ' Female')
(61, ' Female')
(39, ' Male')
(45, ' Female')
(33, ' Female')
(39, ' Male')
(62, ' Female')
(45, ' Male')
(32, ' Female')
(52, ' Male')
(34, ' Male')
(26, ' Female')
(43, ' Female')
(49, ' Male')
(57, ' Female')
(44, ' Male')
(46, ' Female')
(43, ' Female')
(30, ' Female')
(36, ' Female')
(34, ' Male')
(55, ' Male')
(42, ' Female')
(31, ' Male')
(40, ' Male')
(46, ' Female')
(23, ' Male')
(38, ' Female')
(62, ' Male')
(65, ' Female')
(40, ' Male')
(43, ' Male')
(43, ' Female')
(32, ' Female')
(31, ' Male')
(41, ' Female')
(43, ' Female')
(27, ' Female')
(45, ' Female')
(48, ' Male')
(47, ' Male')
(35, ' Female')
(54, ' Male')
(34, ' Female')
(55, ' Female')
(42, ' Male')
(59, ' Male')
(30, ' Male')
(27, ' Male')
(44, ' Female')
(38, ' Female')
(24, ' Male')
(36, ' Female')
(53, ' Male')
(35, ' Male')
(23, ' Female')
(48, ' Male')
(44, ' Female')
(19, ' Female')
(51, ' Male')
(50, ' Male')
(41, ' Male')
(61, ' Female')
(41, ' Male')
(47, ' Female')
(52, ' Male')
(68, ' Female')
(38, ' Female')
(35, ' Female')
(38, ' Male')
(54, ' Female')
(41, ' Female')
(41, ' Female')
(44, ' Male')
(47, ' Female')
(28, ' Female')
(32, ' Female')
(42, ' Male')
(36, ' Female')
(40, ' Male')
(40, ' Female')
(55, ' Female')
(36, ' Female')
(41, ' Female')
(36, ' Female')
(50, ' Male')
(39, ' Female')
(42, ' Male')
(36, ' Male')
(45, ' Female')
(45, ' Female')
(43, ' Male')
(47, ' Female')
(57, ' Male')
(27, ' Male')
(33, ' Female')
(36, ' Male')
(42, ' Male')
(33, ' Male')
(49, ' Male')
(31, ' Male')
(32, ' Female')
(61, ' Male')
(29, ' Female')
(27, ' Female')
(62, ' Female')
(33, ' Female')
(61, ' Female')
(31, ' Female')
(26, ' Female')
(33, ' Male')
(54, ' Male')
(36, ' Male')
(41, ' Male')
(56, ' Male')
(46, ' Male')
(43, ' Male')
(46, ' Male')
(30, ' Male')
(43, ' Female')
(28, ' Male')
(42, ' Female')
(39, ' Female')
(45, ' Female')
(35, ' Male')
(38, ' Male')
(47, ' Female')
(37, ' Female')
(31, ' Female')
(61, ' Female')
(47, ' Female')
(46, ' Female')
(33, ' Female')
(34, ' Female')
(38, ' Female')
(62, ' Male')
(49, ' Female')
(54, ' Male')
(48, ' Female')
(40, ' Female')
(53, ' Male')
(53, ' Female')
(29, ' Male')
(31, ' Female')
(39, ' Female')
(38, ' Female')
(43, ' Female')
(42, ' Female')
(39, ' Male')
(61, ' Female')
(37, ' Female')
(28, ' Female')
(42, ' Female')
(55, ' Female')
(37, ' Female')
(43, ' Male')
(35, ' Male')
(39, ' Female')
(47, ' Female')
(60, ' Male')
(36, ' Female')
(50, ' Female')
(49, ' Male')
(63, ' Female')
(42, ' Female')
(59, ' Female')
(59, ' Female')
(45, ' Female')
(33, ' Female')
(38, ' Female')
(44, ' Male')
(29, ' Male')
(37, ' Female')
(38, ' Female')
(42, ' Male')
(46, ' Female')
(27, ' Male')
(43, ' Male')
(40, ' Female')
(24, ' Female')
(37, ' Female')
(54, ' Female')
(47, ' Male')
(34, ' Female')
(38, ' Male')
(71, ' Female')
(41, ' Male')
(39, ' Male')
(36, ' Female')
(41, ' Female')
(36, ' Male')
(32, ' Female')
(50, ' Female')
(33, ' Female')
(45, ' Female')
(45, ' Female')
(30, ' Male')
(35, ' Female')
(50, ' Male')
(47, ' Male')
(38, ' Male')
(55, ' Female')
(43, ' Male')
(69, ' Female')
(38, ' Female')
(32, ' Female')
(43, ' Male')
(59, ' Female')
(57, ' Male')
(43, ' Male')
(38, ' Male')
(43, ' Female')
(35, ' Female')
(36, ' Female')
(29, ' Female')
(39, ' Male')
(46, ' Female')
(63, ' Male')
(38, ' Female')
(50, ' Female')
(42, ' Male')
(41, ' Female')
(45, ' Male')
(46, ' Female')
(48, ' Female')
(33, ' Female')
(58, ' Female')
(36, ' Female')
(39, ' Male')
(45, ' Male')
(41, ' Female')
(34, ' Female')
(47, ' Female')
(34, ' Female')
(37, ' Female')
(51, ' Female')
(42, ' Male')
(31, ' Female')
(40, ' Male')
(59, ' Male')
(53, ' Female')
(39, ' Female')
(43, ' Male')
(39, ' Female')
(31, ' Male')
(58, ' Female')
(33, ' Male')
(31, ' Female')
(60, ' Male')
(51, ' Female')
(32, ' Male')
(22, ' Female')
(63, ' Female')
(36, ' Female')
(43, ' Female')
(53, ' Male')
(32, ' Female')
(35, ' Female')
(46, ' Female')
(62, ' Female')
(56, ' Male')
(41, ' Female')
(46, ' Male')
(30, ' Female')
(56, ' Female')
(42, ' Female')
(48, ' Female')
(33, ' Female')
(30, ' Female')
(54, ' Male')
(51, ' Male')
(32, ' Female')
(61, ' Female')
(32, ' Female')
(29, ' Female')
(43, ' Male')
(27, ' Female')
(74, ' Female')
(39, ' Female')
(38, ' Female')
(51, ' Male')
(36, ' Male')
(38, ' Male')
(44, ' Female')
(46, ' Male')
(43, ' Male')
(48, ' Male')
(64, ' Male')
(38, ' Male')
(42, ' Male')
(29, ' Female')
(41, ' Female')
(30, ' Female')
(30, ' Male')
(48, ' Male')
(44, ' Female')
(34, ' Male')
(51, ' Male')
(55, ' Female')
(39, ' Female')
(31, ' Male')
(27, ' Male')
(45, ' Male')
(37, ' Female')
(45, ' Female')
(41, ' Female')
(64, ' Male')
(34, ' Female')
(52, ' Female')
(38, ' Female')
(45, ' Female')
(26, ' Male')
(44, ' Male')
(36, ' Male')
(47, ' Male')
(34, ' Male')
(67, ' Female')
(42, ' Male')
(41, ' Male')
(45, ' Female')
(69, ' Female')
(48, ' Female')
(36, ' Female')
(52, ' Female')
(25, ' Female')
(47, ' Female')
(46, ' Female')
(32, ' Male')
(33, ' Male')
(61, ' Female')
(24, ' Female')
(32, ' Female')
(47, ' Female')
(40, ' Female')
(50, ' Female')
(36, ' Female')
(30, ' Female')
(35, ' Female')
(49, ' Female')
(40, ' Female')
(49, ' Female')
(34, ' Female')
(38, ' Female')
(23, ' Female')
(48, ' Male')
(43, ' Female')
(36, ' Male')
(50, ' Female')
(40, ' Female')
(38, ' Female')
(44, ' Female')
(49, ' Male')
(33, ' Female')
(35, ' Female')
(41, ' Female')
(36, ' Female')
(31, ' Male')
(46, ' Female')
(55, ' Male')
(56, ' Female')
(35, ' Female')
(34, ' Female')
(42, ' Female')
(38, ' Male')
(36, ' Female')
(51, ' Male')
(52, ' Female')
(41, ' Female')
(34, ' Male')
(40, ' Female')
(44, ' Female')
(52, ' Male')
(42, ' Female')
(35, ' Female')
(38, ' Male')
(43, ' Male')
(56, ' Female')
(41, ' Male')
(36, ' Male')
(42, ' Female')
(45, ' Female')
(43, ' Male')
(34, ' Female')
(43, ' Female')
(37, ' Female')
(52, ' Female')
(45, ' Female')
(39, ' Female')
(28, ' Female')
(38, ' Male')
(52, ' Female')
(47, ' Male')
(60, ' Male')
(57, ' Female')
(41, ' Male')
(51, ' Female')
(55, ' Female')
(40, ' Male')
(52, ' Male')
(37, ' Male')
(45, ' Male')
(39, ' Female')
(50, ' Female')
(41, ' Female')
(49, ' Female')
(42, ' Male')
(52, ' Male')
(36, ' Male')
(47, ' Female')
(31, ' Female')
(42, ' Female')
(36, ' Male')
(42, ' Female')
(54, ' Male')
(46, ' Male')
(39, ' Female')
(39, ' Male')
(34, ' Female')
(34, ' Male')
(55, ' Female')
(38, ' Female')
(28, ' Male')
(37, ' Male')
(57, ' Male')
(41, ' Male')
(36, ' Male')
(45, ' Female')
(31, ' Male')
(43, ' Female')
(43, ' Female')
(35, ' Male')
(40, ' Male')
(41, ' Female')
(66, ' Female')
(21, ' Female')
(51, ' Male')
(44, ' Female')
(29, ' Female')
(46, ' Female')
(42, ' Male')
(39, ' Female')
(57, ' Male')
(47, ' Female')
(43, ' Female')
(47, ' Female')
(35, ' Female')
(56, ' Female')
(38, ' Male')
(65, ' Male')
(42, ' Male')
(36, ' Female')
(62, ' Male')
(38, ' Female')
(49, ' Male')
(60, ' Female')
(36, ' Female')
(43, ' Male')
(29, ' Female')
(46, ' Female')
(57, ' Female')
(54, ' Male')
(50, ' Female')
(43, ' Female')
(36, ' Female')
(46, ' Female')
(42, ' Male')
(35, ' Female')
(38, ' Male')
(31, ' Male')
(51, ' Female')
(57, ' Female')
(30, ' Male')
(50, ' Female')
(32, ' Female')
(25, ' Female')
(41, ' Male')
(33, ' Female')
(31, ' Female')
(45, ' Female')
(48, ' Female')
(48, ' Female')
(44, ' Male')
(43, ' Male')
(31, ' Male')
(60, ' Female')
(57, ' Female')
(31, ' Male')
(50, ' Male')
(48, ' Male')
(53, ' Female')
(53, ' Female')
(39, ' Male')
(43, ' Female')
(41, ' Female')
(55, ' Female')
(44, ' Female')
(62, ' Female')
(33, ' Male')
(46, ' Female')
(31, ' Female')
(41, ' Male')
(57, ' Male')
(50, ' Female')
(41, ' Female')
(35, ' Male')
(30, ' Female')
(29, ' Male')
(29, ' Male')
(42, ' Male')
(34, ' Female')
(39, ' Female')
(48, ' Female')
(44, ' Male')
(26, ' Male')
(30, ' Female')
(29, ' Male')
(42, ' Female')
(42, ' Male')
(43, ' Female')
(27, ' Female')
(50, ' Male')
(28, ' Female')
(46, ' Male')
(39, ' Male')
(41, ' Male')
(46, ' Female')
(44, ' Female')
(27, ' Female')
(35, ' Female')
(44, ' Female')
(40, ' Male')
(48, ' Female')
(40, ' Female')
(41, ' Male')
(23, ' Female')
(48, ' Female')
(46, ' Female')
(33, ' Female')
(42, ' Female')
(29, ' Male')
(23, ' Male')
(39, ' Female')
(42, ' Male')
(26, ' Female')
(42, ' Female')
(40, ' Male')
(36, ' Female')
(38, ' Female')
(49, ' Female')
(56, ' Female')
(25, ' Male')
(74, ' Female')
(50, ' Female')
(43, ' Female')
(51, ' Female')
(54, ' Female')
(32, ' Female')
(61, ' Female')
(53, ' Female')

(45, ' Female')
(36, ' Female')
(61, ' Female')
(28, ' Female')
(39, ' Female')
(45, ' Female')
(30, ' Female')
(40, ' Female')
(57, ' Male')
(42, ' Female')
(37, ' Female')
(36, ' Male')
(32, ' Male')
(63, ' Female')
(53, ' Female')
(44, ' Female')
(36, ' Female')
(42, ' Male')
(41, ' Female')
(31, ' Female')
(39, ' Female')
(60, ' Female')
(27, ' Male')
(59, ' Male')
(46, ' Female')
(37, ' Male')
(46, ' Male')
(55, ' Female')
(34, ' Female')
(24, ' Female')
(44, ' Male')
(68, ' Female')
(46, ' Female')
(45, ' Male')
(33, ' Male')
(37, ' Female')
(44, ' Male')
(42, ' Male')
(48, ' Male')
(25, ' Male')
(42, ' Male')
(52, ' Female')
(50, ' Female')
(38, ' Female')
(53, ' Male')
(46, ' Female')
(56, ' Male')
(53, ' Female')
(49, ' Female')
(51, ' Female')
(61, ' Female')
(45, ' Male')
(55, ' Female')
(33, ' Male')
(37, ' Male')
(49, ' Male')
(48, ' Female')
(29, ' Female')
(39, ' Male')
(42, ' Female')
(40, ' Male')
(46, ' Male')
(68, ' Male')
(53, ' Male')
(45, ' Female')
(55, ' Male')
(31, ' Female')
(56, ' Female')
(44, ' Female')
(47, ' Male')
(45, ' Male')
(58, ' Female')
(31, ' Male')
(55, ' Female')
(49, ' Female')
(29, ' Female')
(42, ' Female')
(44, ' Female')
(59, ' Male')
(54, ' Female')
(41, ' Male')
(63, ' Female')
(42, ' Male')
(31, ' Male')
(50, ' Female')
(33, ' Female')
(36, ' Male')
(35, ' Female')
(35, ' Female')
(40, ' Female')
(48, ' Female')
(44, ' Female')
(31, ' Male')
(56, ' Female')
(35, ' Female')
(61, ' Male')
(29, ' Female')
(47, ' Female')
(41, ' Female')
(51, ' Female')
(50, ' Female')
(50, ' Female')
(28, ' Male')
(41, ' Female')
(49, ' Male')
(48, ' Female')
(60, ' Male')
(33, ' Female')
(42, ' Male')
(50, ' Female')
(45, ' Female')
(30, ' Female')
(30, ' Male')
(81, ' Female')
(37, ' Female')
(38, ' Female')
(45, ' Female')
(31, ' Female')
(37, ' Female')
(43, ' Female')

## 5. Write two function queries

In [79]:
fn1 = engine.execute('''select sex,max(age), min(age), avg(age) from adult group by(sex)''')
for row in fn1:
    print (row)
#average Divorcing age on available adult data

(' Female', 90, 17, 36.80115618459085)
(' Male', 90, 17, 39.37003225006202)

In [80]:
fn2 = engine.execute('''select native_country,count(sex=" Male"), count(sex=" Female") from adult group by(native_country)''')
for row in fn2:
    print (row)
#count of male & female w.r.t country

(' ?', 535, 535)
(' Cambodia', 16, 16)
(' Canada', 113, 113)
(' China', 69, 69)
(' Columbia', 54, 54)
(' Cuba', 81, 81)
(' Dominican-Republic', 47, 47)
(' Ecuador', 25, 25)
(' El-Salvador', 64, 64)
(' England', 87, 87)
(' France', 29, 29)
(' Germany', 131, 131)
(' Greece', 25, 25)
(' Guatemala', 33, 33)
(' Haiti', 37, 37)
(' Holand-Netherlands', 1, 1)
(' Honduras', 9, 9)
(' Hong', 17, 17)
(' Hungary', 13, 13)
(' India', 93, 93)
(' Iran', 43, 43)
(' Ireland', 23, 23)
(' Italy', 55, 55)
(' Jamaica', 76, 76)
(' Japan', 62, 62)
(' Laos', 13, 13)
(' Mexico', 335, 335)
(' Nicaragua', 27, 27)
(' Outlying-US(Guam-USVI-etc)', 14, 14)
(' Peru', 27, 27)
(' Philippines', 181, 181)
(' Poland', 54, 54)
(' Portugal', 24, 24)
(' Puerto-Rico', 85, 85)
(' Scotland', 11, 11)
(' South', 76, 76)
(' Taiwan', 51, 51)
(' Thailand', 18, 18)
(' Trinadad&Tobago', 16, 16)
(' United-States', 27444, 27444)
(' Vietnam', 59, 59)
(' Yugoslavia', 15, 15)